/* Question bank — based on general U.S. rules of the road (common across state DMV handbooks).
   NOTE: answer positions in this file are NOT balanced on purpose — app.js shuffles the
   display order of choices on every render, so users always see a uniform distribution. */
"use strict";

const CATEGORIES = {
  signs:    { name: "Signs & Signals",   icon: "octagon",   desc: "Shapes, colors, and meanings" },
  markings: { name: "Markings & Lanes",  icon: "lanes",     desc: "Lines, arrows, bike and HOV lanes" },
  row:      { name: "Right of Way",      icon: "crossroad", desc: "Who goes first — the #1 fail topic" },
  speed:    { name: "Speed & Distance",  icon: "gauge",     desc: "Limits, safe speeds, following distance" },
  parking:  { name: "Parking & Stopping",icon: "parking",   desc: "Where and how to park safely" },
  alcohol:  { name: "Alcohol & Drugs",   icon: "ban",       desc: "Limits, penalties, and impairment" },
  safety:   { name: "Safety & Emergencies", icon: "shield", desc: "Belts, night driving, crashes, skids" },
  vulnerable:{ name: "People & Riders",  icon: "users",     desc: "Pedestrians, bikes, motorcycles, animals" },
  vehicle:  { name: "Vehicle Basics",    icon: "wrench",    desc: "Checks, tires, ABS, and maintenance" },
  laws:     { name: "Rules & Penalties", icon: "scale",     desc: "Documents, turns, and the law" },
};

const QUESTIONS = [
  /* ================= SIGNS & SIGNALS ================= */
  { id:"sg01", cat:"signs", signId:"stop", q:"What must you do at this sign?",
    choices:["Slow down and roll through if clear","Come to a COMPLETE stop","Stop only if another car is present","Yield without stopping"],
    a:1, why:"An eight-sided (octagonal) red sign means come to a full stop — wheels fully stopped — at the stop line, crosswalk, or before entering the intersection. Then yield to traffic and pedestrians and go when safe." },
  { id:"sg02", cat:"signs", q:"Why is the STOP sign the only eight-sided (octagon) sign?",
    choices:["So it can be recognized even from behind or covered in snow","It was chosen randomly in the 1920s","To match European designs","Because red paint was cheaper"],
    a:0, why:"The unique octagon shape lets drivers recognize it from any angle — even the back of the sign — or when snow covers the words. Every octagonal sign means STOP, no exceptions." },
  { id:"sg03", cat:"signs", signId:"yield", q:"What does this sign require?",
    choices:["Always come to a complete stop","Give the right of way to traffic and pedestrians; stop if needed","Speed up to merge quickly","Wait for a green light"],
    a:1, why:"A downward-pointing triangle means YIELD: slow down, give the right of way to cross traffic and pedestrians, and be ready to stop. Unlike a stop sign, you may continue without stopping if the way is genuinely clear." },
  { id:"sg04", cat:"signs", signId:"doNotEnter", q:"This sign means:",
    choices:["Road closed to pedestrians","Do not enter this road or ramp","No trucks allowed","Exit only"],
    a:1, why:"A red circle with a white horizontal bar means DO NOT ENTER. It marks one-way streets, exit ramps, and restricted roads — beyond it you would be driving against traffic." },
  { id:"sg05", cat:"signs", signId:"wrongWay", q:"You see this sign facing you. What should you do?",
    choices:["Continue carefully","Pull over, stop, and turn around","Back up on the shoulder at speed","Turn on headlights and keep going"],
    a:1, why:"WRONG WAY means you are driving against traffic — usually on a freeway ramp. Pull to the side immediately, stop, and turn around. WRONG WAY and DO NOT ENTER signs are often paired." },
  { id:"sg06", cat:"signs", signId:"speedLimit", q:"A white rectangular sign showing 'SPEED LIMIT 55' means:",
    choices:["You should drive exactly 55 mph","55 mph is the MAXIMUM legal speed in ideal conditions","55 mph is the minimum speed","Trucks must drive 55"],
    a:1, why:"Posted limits are maximums for ideal conditions. In rain, fog, snow, or heavy traffic you must slow below the limit — the basic speed law requires a speed reasonable for conditions." },
  { id:"sg07", cat:"signs", q:"What is the difference between WHITE and YELLOW signs?",
    choices:["White warns, yellow regulates","White = traffic regulations you must obey; yellow = warnings ahead","Yellow marks rest areas","There is no difference"],
    a:1, why:"White signs are regulatory — they state the law (speed limits, one way, no parking). Yellow (and orange) signs warn you about conditions ahead. Knowing the color system lets you react even before reading." },
  { id:"sg08", cat:"signs", signId:"noUturn", q:"This sign tells you:",
    choices:["No left turns","U-turns are prohibited here","Roundabout ahead","Detour ahead"],
    a:1, why:"A red circle with a slash over a U-turn arrow prohibits U-turns at that location. Where there is no sign, U-turns are generally legal if you can see clearly and make them safely." },
  { id:"sg09", cat:"signs", signId:"oneWay", q:"This sign means:",
    choices:["Traffic flows only in the direction of the arrow","Merging traffic ahead","Passing lane ahead","Detour ahead"],
    a:0, why:"ONE WAY with an arrow means all traffic on that street moves only in the arrow's direction. Never turn against it — and remember you can only turn onto it in the arrow's direction." },
  { id:"sg10", cat:"signs", signId:"railCrossing", q:"This round yellow sign means:",
    choices:["Roundabout ahead","A railroad crossing is ahead","Rest area ahead","One-lane bridge ahead"],
    a:1, why:"A ROUND yellow sign with a black X and 'RR' warns of a railroad crossing ahead. Slow down, look and listen for trains, and never start across unless you can clear the tracks completely." },
  { id:"sg11", cat:"signs", q:"When you approach a railroad crossing with flashing red lights and lowered gates, you must:",
    choices:["Speed up to beat the train","Stop between 15 and 50 feet from the crossing and wait","Honk and cross slowly","Stop directly on the tracks"],
    a:1, why:"Flashing red lights and gates mean a train is coming. Stop well before the crossing (roughly 15–50 feet back) and wait until the lights stop and the gates rise. Never drive around gates or stop on the tracks." },
  { id:"sg12", cat:"signs", signId:"pedCrossing", q:"This diamond sign means:",
    choices:["School zone","Pedestrian crossing ahead","No walking allowed","Crossroad ahead"],
    a:1, why:"A yellow diamond with a walking figure warns of a pedestrian crossing. Slow down, check the sidewalks, and be prepared to stop — pedestrians have the right of way in the crosswalk." },
  { id:"sg13", cat:"signs", signId:"schoolZone", q:"A five-sided (pentagon) yellow-green sign means:",
    choices:["A hospital is ahead","A school zone or school crossing is ahead","A national park entrance","A highway cloverleaf"],
    a:1, why:"The pentagon shape and fluorescent yellow-green color are reserved for schools. Slow to the posted school speed, watch for children, and obey crossing guards — children are unpredictable near roads." },
  { id:"sg14", cat:"signs", signId:"deerCrossing", q:"This sign warns that:",
    choices:["Cattle ranch ahead","Wild animals often cross here","Horseback riders only","Zoo entrance ahead"],
    a:1, why:"A deer (or other animal) crossing sign marks an area where animals frequently cross, often at dawn and dusk. Slow down and stay alert — animals rarely cross alone; if one appears, more may follow." },
  { id:"sg15", cat:"signs", signId:"slippery", q:"This sign means:",
    choices:["Winding road","Slippery when wet","Washboard surface","Trucks carrying liquids"],
    a:1, why:"A car with wavy skid marks means the pavement is unusually slippery when wet — common on bridges, in shade, and on roads with oil buildup. Slow down before curves and avoid sudden braking or steering." },
  { id:"sg16", cat:"signs", signId:"merge", q:"This sign means:",
    choices:["Lane ends ahead — merge","Merging traffic enters your road ahead","Two roads cross ahead","Your lane becomes a turn lane"],
    a:1, why:"Merging traffic (a side arrow joining the main arrow) means vehicles will enter your roadway ahead. Drivers on the through road and merging drivers SHARE the job: adjust speed and open a gap." },
  { id:"sg17", cat:"signs", signId:"dividedHighwayBegins", q:"This sign means:",
    choices:["The divided highway is ending","A divided highway begins ahead — keep right of the median","Two lanes merge into one","A tunnel is ahead"],
    a:1, why:"'Divided highway begins' warns that the road ahead has a median with opposing traffic on the far side. Keep to the RIGHT of the divider and don't cross it." },
  { id:"sg18", cat:"signs", signId:"twoWayTraffic", q:"This sign warns that:",
    choices:["A one-way street begins","Two-way traffic is ahead — oncoming traffic in the other lane","A passing zone begins","The road splits"],
    a:1, why:"Opposing up/down arrows mean you are entering (or on) a two-way road. Keep right and only pass where the road is clear and passing is legal." },
  { id:"sg19", cat:"signs", signId:"roundabout", q:"When you see this sign, you should:",
    choices:["Speed up to get through quickly","Slow down and prepare to yield to traffic already in the circle","Stop completely before entering","Enter to the left of the island"],
    a:1, why:"A roundabout sign means a circular intersection ahead. Slow down, yield to traffic already circulating, enter to the RIGHT of the central island, travel counterclockwise, and use your turn signal to exit." },
  { id:"sg20", cat:"signs", signId:"workZone", q:"What does an ORANGE sign indicate?",
    choices:["A school area","A temporary warning — road work or construction zone","A detour for trucks only","An evacuation route"],
    a:1, why:"Orange is used only for construction and maintenance zones. Slow down, increase following distance, watch for workers and equipment, and obey posted reduced limits — fines are often doubled in work zones." },
  { id:"sg21", cat:"signs", signId:"flagger", q:"In a work zone, a flagger's instructions:",
    choices:["Are only suggestions","Override signs, signals, and even police directions","Apply only to trucks","Must be obeyed only during work hours"],
    a:1, why:"A flagger's directions have priority over everything else — signs, signals, and markings. Slow down well before reaching them and follow their signals exactly; they protect both workers and you." },
  { id:"sg22", cat:"signs", signId:"hospital", q:"A BLUE square sign like this marks:",
    choices:["A parking area","Driver services — here, a hospital","A scenic route","A police station"],
    a:1, why:"Blue signs list motorist services: hospitals, gas, food, lodging, rest areas. Green signs give guidance (directions/exits), and brown marks recreation areas." },
  { id:"sg23", cat:"signs", signId:"noParking", q:"This sign means:",
    choices:["You may park for 5 minutes only","You may not park here","No stopping or standing at any time","Parking for residents only"],
    a:1, why:"No PARKING means you can't leave your vehicle, though you may briefly stop to load or unload. 'No Standing' and 'No Stopping' signs are stricter — you may not pause there at all." },
  { id:"sg24", cat:"signs", signId:"signalAhead", q:"This sign tells you:",
    choices:["A traffic signal is ahead — be ready to stop","A fire station is ahead","A railroad signal is ahead","Street lighting ends"],
    a:0, why:"A traffic-signal sign warns of a signal that's hidden by a curve, hill, or trees. Ease off the gas, check behind you, and prepare to stop if the light is changing." },
  { id:"sg25", cat:"signs", signId:"stopAhead", q:"This sign means:",
    choices:["Stop here","A stop sign is ahead — begin slowing now","Yield ahead","All traffic must turn"],
    a:1, why:"A yellow diamond showing a stop sign warns that a STOP sign is ahead, often hard to see. Start braking early rather than making a panic stop at the sign." },
  { id:"sg26", cat:"signs", signId:"bikeCrossing", q:"This sign means:",
    choices:["Bicycle parking ahead","Bicyclists cross or share the road ahead","No bicycles allowed","Bike repair shop ahead"],
    a:1, why:"Watch for riders crossing or sharing the road. Slow down, check blind spots before turning right, and give cyclists at least 3 feet (1 m) of clearance when passing." },
  { id:"sg27", cat:"signs", signId:"chevron", q:"A large chevron sign like this is posted:",
    choices:["At rest areas","On the OUTSIDE of sharp curves","At every railroad crossing","In parking garages"],
    a:1, why:"Chevrons mark the outside of a sharp curve, pointing the direction of the bend. Slow down BEFORE the curve, stay in your lane, and avoid braking mid-curve." },
  { id:"sg28", cat:"signs", signId:"keepRight", q:"This white sign means:",
    choices:["Pass on the right","Keep right of the island or obstruction ahead","Right lane ends","Right turn only"],
    a:1, why:"Keep Right (a black arrow bending around a dot) means an island, median, or obstruction is ahead — pass on its right side." },
  { id:"sg29", cat:"signs", q:"A flashing RED traffic light means:",
    choices:["Proceed with caution without stopping","Treat it like a STOP sign — stop fully, then go when safe","The light is broken — ignore it","Stop and wait for green"],
    a:1, why:"A flashing red light = stop sign rules. Come to a complete stop, yield to traffic and pedestrians, then proceed when clear. (A flashing YELLOW just means slow down and proceed with caution.)" },
  { id:"sg30", cat:"signs", q:"A steady YELLOW traffic light means:",
    choices:["Speed up to clear the intersection","The light is about to turn red — stop if you can do so safely","Stop only if a police officer is present","Yield to pedestrians only"],
    a:1, why:"Yellow means the signal is about to turn red. Stop before the intersection if you can do it safely; if you're too close to stop, continue through with care. Never accelerate to 'beat the light.'" },
  { id:"sg31", cat:"signs", q:"A GREEN traffic light means:",
    choices:["You have the right of way over everything","Go if the intersection is clear — still yield to pedestrians and vehicles already in it","Slow down before entering","Go only if no cars are waiting"],
    a:1, why:"Green means go IF the intersection is clear. You must still yield to pedestrians and to any vehicle already in the intersection — and never enter (even on green) if traffic would trap you inside." },
  { id:"sg32", cat:"signs", q:"A YELLOW light that has been green for a while is often called a 'stale' green. The best action is:",
    choices:["Maintain speed and expect it to stay green","Cover the brake, check mirrors, and be ready to stop","Accelerate to make it through","Stop immediately wherever you are"],
    a:1, why:"A 'stale' green (long-lit, or pedestrian signals counting down) may change any moment. Ease off the gas, cover the brake, and check your mirror so you can stop safely if it turns yellow." },
  { id:"sg33", cat:"signs", q:"A solid YELLOW line beside a BROKEN yellow line on your side means:",
    choices:["You may pass any time","You may pass when safe ONLY if the broken line is on your side","Passing is prohibited for everyone","The road is one-way"],
    a:1, why:"On two-way roads, a broken yellow line on YOUR side means passing is allowed when safe. If the solid line is on your side, you may not cross it to pass — oncoming traffic may." },
  { id:"sg34", cat:"signs", q:"A GREEN arrow traffic light means:",
    choices:["Prepare to stop","A protected turn — oncoming traffic is stopped, but still yield to pedestrians","Yield to all traffic first","The signal is out of order"],
    a:1, why:"A green arrow is a PROTECTED movement: oncoming traffic faces red. You may turn without yielding to oncoming cars, but you must still yield to pedestrians in the crosswalk." },
  { id:"sg35", cat:"signs", signId:"noPassingZone", q:"This pennant-shaped sign marks:",
    choices:["The end of a passing zone","The START of a no-passing zone","A passing lane ahead","A recreation area"],
    a:1, why:"The yellow pennant is posted on the LEFT side of the road at the beginning of a no-passing zone. Do not cross the center line to pass until the zone ends (solid yellow line or 'pass with care' sign)." },

  /* ================= RIGHT OF WAY ================= */
  { id:"rw01", cat:"row", q:"Two cars reach a 4-way stop at exactly the same time. Who goes first?",
    choices:["The car on the LEFT","The car on the RIGHT","Whoever arrived faster","The bigger vehicle"],
    a:1, why:"When two vehicles arrive simultaneously at an all-way stop, the driver on the RIGHT has the right of way. If you're the left car, yield, make eye contact, and proceed after they move." },
  { id:"rw02", cat:"row", q:"You're turning left at an intersection with a green light (no arrow). Oncoming traffic is going straight. Who has the right of way?",
    choices:["You, because you arrived first","The oncoming through traffic","Whoever signals first","Neither — both must stop"],
    a:1, why:"On a plain green ball, a left turn must YIELD to oncoming traffic and pedestrians. Only turn when there's a safe gap — or wait for a green arrow, which protects your turn." },
  { id:"rw03", cat:"row", q:"You're pulling out of a driveway or parking lot. You must:",
    choices:["Yield to pedestrians on the sidewalk and to all traffic on the road","Go quickly — traffic will slow for you","Honk and pull out","Stop only for cars, not people"],
    a:0, why:"Vehicles entering the roadway from a driveway, alley, or parking lot yield to EVERYTHING: pedestrians on the sidewalk first, then all traffic on the road. Sidewalk users always have priority." },
  { id:"rw04", cat:"row", q:"An emergency vehicle with sirens and flashing lights approaches. You should:",
    choices:["Speed up to clear the intersection","Pull over to the right edge of the road and stop until it passes","Stop exactly where you are, even in an intersection","Follow closely to get through traffic"],
    a:1, why:"State laws require you to pull toward the RIGHT edge (or curb), stop, and stay there until the emergency vehicle passes. Don't block an intersection — clear it first if you're in one." },
  { id:"rw05", cat:"row", q:"A blind pedestrian with a white cane or guide dog steps to the curb. You must:",
    choices:["Honk so they know you're there","Stop completely and yield — don't startle or crowd them","Wave them across from your window","Drive around them slowly"],
    a:1, why:"You must stop and yield the full right of way to blind pedestrians (white cane or guide dog). Never honk — the sound can confuse them. Remain stopped until they're safely across." },
  { id:"rw06", cat:"row", q:"At an uncontrolled intersection (no signs or signals), two cars arrive at the same time:",
    choices:["The faster car goes first","The car on the right goes first","The car going straight goes first","The newer car goes first"],
    a:1, why:"Same rule as a 4-way stop: first to arrive goes first; if simultaneous, yield to the vehicle on your RIGHT. Slow down approaching any uncontrolled intersection — never assume the other driver sees you." },
  { id:"rw07", cat:"row", q:"At a T-intersection, a car on the road that ENDS must yield to:",
    choices:["The car on the through road","The car that signals first","The smaller vehicle","Nobody — it's first come, first served"],
    a:0, why:"At a T-intersection, traffic on the terminating road yields to traffic on the continuing (through) road, because through traffic isn't expecting cross traffic." },
  { id:"rw08", cat:"row", q:"A pedestrian is crossing at a marked crosswalk with no signal. You should:",
    choices:["Honk for them to hurry","Yield — stop and let them finish crossing","Drive around them if there's room","Keep moving; cars have priority"],
    a:1, why:"Pedestrians have the right of way in marked and unmarked crosswalks. You must stop and wait — and never pass another vehicle that has stopped for a crosswalk (they may be hiding a person)." },
  { id:"rw09", cat:"row", q:"A school bus with flashing RED lights is stopped on your side of an undivided road. You must:",
    choices:["Pass slowly on the left","Stop, whichever direction you're traveling, until the lights stop","Pass if no children are visible","Keep moving — only the bus must stop"],
    a:1, why:"On an UNDIVIDED road, traffic in BOTH directions must stop for a school bus's flashing red lights and stay stopped until they're off (and the stop arm withdraws). Children cross in front of the bus." },
  { id:"rw10", cat:"row", q:"A school bus with flashing red lights is stopped on the OTHER side of a divided road with a median. You should:",
    choices:["Stop anyway, like all traffic","Proceed with caution — only traffic behind the bus must stop","Back up and take another route","Speed past before children exit"],
    a:1, why:"On a divided highway separated by a median (or barrier), only traffic traveling in the same direction as the bus must stop. Still, slow down and watch for children near the road." },
  { id:"rw11", cat:"row", q:"Entering a roundabout, you must yield to:",
    choices:["Traffic entering after you","Traffic already circulating in the roundabout","Nobody — first in wins","Only large vehicles"],
    a:1, why:"Vehicles already IN the roundabout have the right of way. Wait for a gap at the yield line, enter to the right of the island, go counterclockwise, signal, and exit." },
  { id:"rw12", cat:"row", q:"You're merging onto a freeway. Who has the right of way?",
    choices:["You — freeway traffic must move over","Freeway traffic already on the highway","Whichever car is faster","The vehicle in the right lane at all times"],
    a:1, why:"Merging traffic yields to highway traffic. Use the acceleration lane to match highway speed, find a gap, and merge smoothly. That said, courtesy (moving over or adjusting speed) prevents collisions." },
  { id:"rw13", cat:"row", q:"You're backing out of a parking space. You must:",
    choices:["Yield to all traffic and pedestrians","Expect others to stop for you","Back out quickly to claim the lane","Honk continuously while backing"],
    a:0, why:"A backing vehicle NEVER has the right of way. Check mirrors and physically look over your shoulder, back slowly, and yield to everyone — pedestrians and moving vehicles." },
  { id:"rw14", cat:"row", q:"The light is green, but traffic ahead has stopped and you'd be stuck IN the intersection. What should you do?",
    choices:["Enter and wait for traffic to move","Wait behind the crosswalk until you can clear the intersection completely","Creep forward slowly","Enter and turn on hazards"],
    a:1, why:"Never enter an intersection you can't clear — this 'blocks the box' and gridlocks cross traffic. Wait at the stop line until there's room to fully cross, even on a green light." },
  { id:"rw15", cat:"row", q:"You want to turn right across a bike lane at an intersection. You must:",
    choices:["Turn quickly — cyclists must stop","Yield to bicyclists in the bike lane before crossing it","Honk to clear the lane","Use the bike lane as a turning lane early"],
    a:1, why:"Cyclists in the bike lane have the right of way. Merge into the lane only after yielding, and always check the blind spot over your right shoulder — a common spot for 'right-hook' crashes." },
  { id:"rw16", cat:"row", q:"A police, ambulance, or fire vehicle is stopped on the roadside with flashing lights. You should:",
    choices:["Maintain speed and pass closely","Move over a lane away from them if safe, or slow down significantly","Stop completely behind them","Photograph the scene while passing"],
    a:1, why:"'Move Over' laws require drivers to change lanes away from stopped emergency vehicles when safely possible; if you can't change lanes, slow down well below the limit. This protects responders and stranded drivers." },
  { id:"rw17", cat:"row", q:"An oncoming driver at night flashes their headlights at you while your high beams are on. You should:",
    choices:["Flash back to warn them","Switch to low beams — you're probably blinding them","Turn your lights off","Keep the high beams; they're safer"],
    a:1, why:"High beams can blind oncoming drivers for hundreds of feet. A flash from oncoming traffic usually means you're dazzling them — switch to low beams promptly." },
  { id:"rw18", cat:"row", q:"You approach a crosswalk where a pedestrian who is blind is waiting with a guide dog. The signal changes to green for you. You should:",
    choices:["Proceed — your light is green","Yield to the pedestrian","Creep forward to prompt them","Sound your horn lightly"],
    a:1, why:"Regardless of the signal, blind pedestrians (white cane or guide dog) always have the absolute right of way. Stop and let them cross fully — never honk or nudge forward." },
  { id:"rw19", cat:"row", q:"Two vehicles meet on a narrow mountain road where only one can pass. Who yields?",
    choices:["The vehicle going uphill","The vehicle going DOWNHILL","The heavier vehicle","Whoever is local"],
    a:1, why:"The driver going UPHILL has the right of way — it's harder to restart on a grade. The downhill vehicle should pull over or back up to a wide spot. (Any vehicle should yield to buses and trucks.)" },

  /* ================= SPEED & DISTANCE ================= */
  { id:"sp01", cat:"speed", q:"The 'basic speed law' says you must:",
    choices:["Always drive at the posted limit","Never drive faster than is safe for current conditions","Drive at least the posted limit","Match the speed of traffic exactly"],
    a:1, why:"The basic speed law overrides the posted number: you can be cited for driving the limit in fog, rain, or heavy traffic if it's unsafe. You may also be cited for driving too SLOWLY and obstructing traffic." },
  { id:"sp02", cat:"speed", q:"In good conditions, your following distance should be at least:",
    choices:["1 second behind the car ahead","2 seconds","3 seconds","Half a car length"],
    a:2, why:"Use the 3-second rule: pick a fixed object; when the car ahead passes it, count 'one-thousand-one…' — you should reach it no sooner than 3 seconds. Add time for rain (4s), and snow/ice or night (5–6s+)." },
  { id:"sp03", cat:"speed", q:"When may you legally exceed the posted speed limit to pass a car?",
    choices:["When the other car is going 10 under","Never","Only on freeways","Only during daylight"],
    a:1, why:"The posted limit applies at all times — passing is not an exception. If the vehicle ahead is at the limit, there's nothing to legally gain by passing." },
  { id:"sp04", cat:"speed", q:"If you double your speed, your stopping distance becomes roughly:",
    choices:["Twice as long","Three times as long","Four times as long","Unchanged — brakes compensate"],
    a:2, why:"Kinetic energy grows with the SQUARE of speed: double the speed ≈ 4× the energy to dissipate, so braking distance roughly quadruples. This is why speed dramatically worsens crash severity." },
  { id:"sp05", cat:"speed", q:"Your car starts to hydroplane. What should you do?",
    choices:["Brake hard immediately","Ease off the accelerator and steer straight","Accelerate to cut through the water","Turn sharply toward the shoulder"],
    a:1, why:"Hydroplaning (tires riding on water, losing contact) can start as slow as 35 mph. Don't brake or turn abruptly — ease off the gas, hold the wheel straight, and let the car slow until the tires grip again." },
  { id:"sp06", cat:"speed", q:"On a freeway entrance ramp, you should:",
    choices:["Slow down before merging","Use the acceleration lane to reach the speed of freeway traffic, then merge into a gap","Stop and wait for a huge gap","Merge immediately, regardless of speed"],
    a:1, why:"The safest merge is at (or near) the speed of highway traffic. Use the full acceleration lane, signal, check mirrors and blind spot, then merge smoothly into an available gap." },
  { id:"sp07", cat:"speed", q:"In heavy fog, the safest approach is to:",
    choices:["Use high beams to see farther","Slow down, use LOW beams, and increase following distance","Turn off your lights to reduce glare","Tailgate so you don't lose the car ahead"],
    a:1, why:"High beams reflect off fog and make things WORSE. Slow way down (often well below the limit), use low beams (fog lights if you have them), and never follow taillights closely — that's how fog pileups happen." },
  { id:"sp08", cat:"speed", q:"Approaching the crest of a hill where you can't see beyond it, you should:",
    choices:["Maintain speed — you have the right of way","Slow down and keep right","Speed up to get over the hill faster","Flash your headlights"],
    a:1, why:"Hidden hazards — stalled cars, pedestrians, animals, or a slow vehicle — may be just over the crest. Slow down and stay right so you can stop within the distance you can see." },
  { id:"sp09", cat:"speed", q:"Driving much slower than the flow of traffic:",
    choices:["Is always the safest choice","Can be illegal and dangerous — it disrupts the traffic flow","Is required in the left lane","Is only illegal for trucks"],
    a:1, why:"On highways, driving too slowly is a citation-worthy hazard: it forces evasive lane changes around you. Keep right if you're slower than traffic; on freeways, minimum-limit laws apply." },
  { id:"sp10", cat:"speed", q:"In a work zone with posted reduced speed limits:",
    choices:["The lower limit applies only when workers are present","You must obey the posted work-zone limit — fines are often doubled","The limit is advisory only","You may keep 5 mph over"],
    a:1, why:"Work-zone speed limits are enforceable regulations, often with doubled fines, and in many states they apply whether or not workers are visible. Slow down early — workers may be just beyond equipment." },
  { id:"sp11", cat:"speed", q:"When following a large truck on a downgrade, you should:",
    choices:["Tailgate to draft behind it","Increase your following distance substantially","Pass quickly on the shoulder","Turn off overdrive"],
    a:1, why:"Trucks slow and maneuver unpredictably on hills (they shift and brake heavily), and you need more room to see around them. Add seconds to your following distance downhill and when visibility is blocked." },
  { id:"sp12", cat:"speed", q:"The speed shown on a yellow curve or ramp advisory sign is:",
    choices:["The legal speed limit for the curve","A RECOMMENDED safe speed for the curve in good conditions","A truck-only limit","The minimum speed"],
    a:1, why:"Advisory speeds on yellow signs are engineering recommendations for ideal conditions — not legal limits. But ignoring them in rain or with a top-heavy vehicle is how rollovers and run-off-road crashes happen." },
  { id:"sp13", cat:"speed", q:"How much distance do you need to pass safely on a two-lane road?",
    choices:["About 5 seconds of clear road","Enough to return without forcing the passed car to brake — often 1/3 mile or more","Whatever feels comfortable","Passing is illegal on two-lane roads"],
    a:1, why:"At 55 mph you cover ~80 ft/second; a safe pass needs clear sight distance for the ENTIRE maneuver (accelerate, pass, and return with room). If you'd cut off the passed vehicle or oncoming traffic appears — abort." },
  { id:"sp14", cat:"speed", q:"Night driving is more dangerous mainly because:",
    choices:["Roads are wetter at night","You can see less — reduce speed and increase following distance","There is more traffic","Cars are harder to hear"],
    a:1, why:"Fatality rates are far higher at night due to reduced visibility, fatigue, and more impaired drivers. Slow down so your stopping distance stays within your headlight range, and never out-drive your lights." },

  /* ================= PARKING & STOPPING ================= */
  { id:"pk01", cat:"parking", q:"Parking facing DOWNHILL with a curb, you should turn your wheels:",
    choices:["Away from the curb (left)","Toward the curb (right)","Straight ahead","It doesn't matter if you use the parking brake"],
    a:1, why:"Downhill + curb: turn wheels TOWARD the curb (right) so if brakes fail the car rolls into the curb, not traffic. Set the parking brake and leave the car in low gear (or Park)." },
  { id:"pk02", cat:"parking", q:"Parking facing UPHILL with a curb, you should turn your wheels:",
    choices:["Toward the curb (right)","Away from the curb (left), letting the car roll back slightly to touch it","Straight ahead","Fully lock either direction"],
    a:1, why:"Uphill + curb: turn wheels AWAY from the curb and ease back so a tire rests against it — the car rolls OFF the road if it slips. (With NO curb, turn wheels toward the edge of the road both ways.)" },
  { id:"pk03", cat:"parking", q:"When parallel parked, your wheels should be no more than:",
    choices:["6 inches from the curb","12–18 inches from the curb","3 feet from the curb","Anywhere within the lane"],
    a:1, why:"Most states require parallel-parked cars within 12–18 inches of the curb. Practicing curb distance is a common road-test scoring point — and prevents sideswipes by passing traffic." },
  { id:"pk04", cat:"parking", q:"Which of these is ALWAYS illegal?",
    choices:["Parking on a residential street overnight","Double parking (stopping beside a parked car)","Parking facing uphill","Parking without passengers"],
    a:1, why:"Double parking blocks a travel lane and is illegal everywhere. Also always illegal: parking in intersections, crosswalks, sidewalks, bus stops, in front of driveways and fire hydrants, and on bridges/tunnels." },
  { id:"pk05", cat:"parking", q:"You may never park within how far of a fire hydrant?",
    choices:["5 feet","15 feet (or as posted)","50 feet","100 feet"],
    a:1, why:"The common rule is at least 15 feet from a fire hydrant (some states differ slightly). Fire crews needs room to run hoses — blocking a hydrant risks lives and earns a hefty ticket or tow." },
  { id:"pk06", cat:"parking", q:"Before exiting your parked car into traffic, you should:",
    choices:["Open the door slowly and hope for the best","Check mirrors and look over your shoulder for traffic, cyclists, and pedestrians","Push the door open quickly","Exit on the driver's side only, always"],
    a:1, why:"'Dooring' a cyclist is dangerous and usually the driver's fault. Check the mirror and blind spot, then open with your far hand (the 'Dutch reach') so your body naturally turns to look." },
  { id:"pk07", cat:"parking", q:"A curb painted RED typically means:",
    choices:["Loading zone only","No stopping, standing, or parking (often fire lanes)","15-minute parking","Disabled permit parking"],
    a:1, why:"Red curb = no stopping at all (commonly fire lanes). Yellow = loading/commercial; white = very brief passenger pickup; blue = disabled permit only; green = limited-time parking." },
  { id:"pk08", cat:"parking", q:"A curb or sign marked BLUE means:",
    choices:["Police vehicles only","Parking only with a disabled person placard or plate","No parking before noon","Electric vehicle charging"],
    a:1, why:"Blue marks accessible parking. Parking there without a valid disability placard/plate brings some of the largest parking fines — and takes the space from someone who needs it." },
  { id:"pk09", cat:"parking", q:"You must stop on the shoulder of a highway at night. What should you do?",
    choices:["Turn on hazard lights and pull as far off the road as possible","Stay in the travel lane with hazards on","Stand behind the car to warn traffic","Turn off all lights to be less noticeable"],
    a:0, why:"Pull as far onto the shoulder as possible, turn on hazard flashers, and stay belted inside, well off traffic. Never stand behind or near the car — passing drivers drift toward what they stare at." },
  { id:"pk10", cat:"parking", q:"When leaving a parallel parking space, you must:",
    choices:["Signal, check traffic and blind spot, and yield to all traffic","Back out fast to force others to yield","Wait for someone to stop and let you out","Use hazards and go"],
    a:0, why:"You're entering traffic from a parked position — you have NO right of way. Signal, check mirrors and blind spot, reverse only until visible, then pull out into a safe gap." },
  { id:"pk11", cat:"parking", q:"It is illegal to park (or stop) in all of these EXCEPT:",
    choices:["In a crosswalk","On a crosswalk side of a stopped school bus loading zone","In a marked legal parking space along the curb","Blocking a driveway"],
    a:2, why:"Legal where permitted: curbside spaces without restrictive signs. The others — crosswalks, school loading zones, blocked driveways, intersections, sidewalks, fire hydrants, bus stops — are always illegal." },
  { id:"pk12", cat:"parking", q:"On a one-way street, you may generally park:",
    choices:["Only on the right side, facing the direction of travel","On either side, with wheels facing the curb direction as posted","Only during daylight","Facing against traffic on the right"],
    a:1, why:"Many states allow parking on EITHER side of a one-way street (left curb included), as long as the car faces the direction traffic flows on that side. Two-way streets: right side only." },
  { id:"pk13", cat:"parking", q:"Hill parking (turning the wheels) exists because:",
    choices:["It looks neat","If the brakes fail, the car rolls off the road instead of into traffic","It helps the steering system","It's required only for manual transmissions"],
    a:1, why:"Turning the wheels is a mechanical backup: if the parking brake or transmission fails on a grade, the car rolls into the curb or shoulder instead of freewheeling into traffic or a pedestrian." },

  /* ================= ALCOHOL & DRUGS ================= */
  { id:"al01", cat:"alcohol", q:"For drivers 21 and over, the general per-se BAC limit is:",
    choices:["0.10%","0.08%","0.05%","0.02%"],
    a:1, why:"0.08% BAC is the per-se DUI limit in most U.S. states (some are lower, e.g. 0.05% in Utah). You can also be convicted BELOW the limit if driving is visibly impaired." },
  { id:"al02", cat:"alcohol", q:"For drivers UNDER 21, most states enforce:",
    choices:["The same 0.08% limit","Zero tolerance — essentially any alcohol (0.01–0.02%) is a violation","0.05% tolerance","No limit at all"],
    a:1, why:"'Zero tolerance' laws set the under-21 limit near zero (typically 0.01–0.02%, which even mouthwash could trip). Under-21 drinkers lose their license quickly — usually on a first offense." },
  { id:"al03", cat:"alcohol", q:"What is the ONLY thing that reduces your blood alcohol content?",
    choices:["Coffee","A cold shower","Food and water","Time"],
    a:3, why:"Your liver eliminates alcohol at a fixed rate (roughly one standard drink per hour). Coffee, showers, food, and exercise make you FEEL more alert but do NOT lower BAC — only time works." },
  { id:"al04", cat:"alcohol", q:"Alcohol FIRST affects which driving ability?",
    choices:["Steering precision","Judgment and self-control","Night vision","Hearing"],
    a:1, why:"Judgment and inhibition degrade at BAC levels far below the legal limit — which is why impaired drivers feel 'fine to drive' while their risk has already doubled. Coordination and reaction come next." },
  { id:"al05", cat:"alcohol", q:"Which of these contains roughly the SAME amount of alcohol?",
    choices:["12 oz beer, 5 oz wine, 1.5 oz of 80-proof spirits","A 6-pack of beer and one glass of wine","One shot and one bottle of wine","All drinks, regardless of size"],
    a:0, why:"One standard drink ≈ 12 oz of 5% beer ≈ 5 oz of 12% wine ≈ 1.5 oz of 40% (80-proof) liquor. Counting 'drinks' only works if you know the standard sizes — a large craft beer can equal 2–3 drinks." },
  { id:"al06", cat:"alcohol", q:"Refusing a lawfully requested breath or blood test usually results in:",
    choices:["Nothing — you can't be forced","Automatic license suspension under implied-consent laws","A fine only","A warning"],
    a:1, why:"By driving, you've already consented to chemical testing ('implied consent'). Refusal typically triggers automatic license suspension (often longer than a DUI itself) and can be used against you in court." },
  { id:"al07", cat:"alcohol", q:"An open container of alcohol in the passenger area of a car is:",
    choices:["Legal if the driver isn't drinking","Illegal in nearly every state, for drivers AND passengers","Legal on private roads only","Legal if the cap is on"],
    a:1, why:"Open-container laws prohibit open alcohol in the passenger compartment — even for passengers, even resealed. Carry it in the trunk or a locked glove compartment where state law allows." },
  { id:"al08", cat:"alcohol", q:"A first DUI conviction typically brings:",
    choices:["A warning letter","License suspension, heavy fines, alcohol education, and possible jail","Points only","License revocation for life"],
    a:1, why:"Even a FIRST DUI commonly means license suspension, thousands in fines and fees, mandatory alcohol classes, probation, possible jail time, and hugely increased insurance costs. Penalties grow fast with repeat offenses." },
  { id:"al09", cat:"alcohol", q:"Prescription or over-the-counter medicines:",
    choices:["Never affect driving","Can impair driving — it's illegal to drive while impaired by ANY drug","Are fine if prescribed by a doctor","Only matter for commercial drivers"],
    a:1, why:"DUI covers drugs — legal or not. Antihistamines, painkillers, sleep aids, and anxiety meds can cause drowsiness and slow reactions. If the label warns against driving, obey it." },
  { id:"al10", cat:"alcohol", q:"Marijuana use before driving:",
    choices:["Improves focus","Impairs judgment, coordination, and reaction time — and is illegal","Is legal in all states","Only matters for teen drivers"],
    a:1, why:"THC impairs distance judgment, reaction time, and lane tracking. Driving high is a drug-impaired (DUID) offense in every state, and combining cannabis with alcohol multiplies impairment." },
  { id:"al11", cat:"alcohol", q:"The safest plan if you'll be drinking is:",
    choices:["Drink only beer","A designated sober driver, rideshare, or public transit — decided BEFORE you go","Wait 30 minutes after the last drink","Eat a big meal first"],
    a:1, why:"Decide the safe ride before the first drink, when judgment is intact. Waiting 'a while' or eating doesn't reliably sober anyone up — plans made while impaired fail." },

  /* ================= SAFETY & EMERGENCIES ================= */
  { id:"sf01", cat:"safety", q:"Seat belts must be worn by:",
    choices:["The driver only","The driver and front passengers only","The driver and ALL passengers, front and back","Adults in back only"],
    a:2, why:"Most states require belts for everyone in the car. An unbelted rear passenger becomes a projectile that can kill people in the front — and belts cut crash deaths roughly in half." },
  { id:"sf02", cat:"safety", q:"An airbag deploys. To stay safe, sit at least ___ from the steering wheel and never place a rear-facing child seat in front of one.",
    choices:["4 inches","10 inches","24 inches","40 inches"],
    a:1, why:"Keep ~10 inches between your breastbone and the wheel, angled slightly back, hands at 9-and-3. Children under 13 belong in the BACK seat — away from deploying airbags." },
  { id:"sf03", cat:"safety", q:"You must use headlights:",
    choices:["Only at midnight to 5 a.m.","Sunset to sunrise, and whenever visibility is poor (or wipers are on)","Only on highways","Only when raining"],
    a:1, why:"Headlights are required from sunset to sunrise and in rain, fog, snow — many states require them whenever wipers run. Lights aren't just to see: they help others SEE you (and it's the law)." },
  { id:"sf04", cat:"safety", q:"You must dim your high beams when an oncoming vehicle is within about:",
    choices:["100 feet","500 feet","1,500 feet","You never need to dim them"],
    a:1, why:"Dim high beams within ~500 feet of an oncoming vehicle and ~300 feet (one car-length x ~30) when following — glare blinds other drivers for seconds after you pass." },
  { id:"sf05", cat:"safety", q:"Oncoming headlights blind you at night. You should:",
    choices:["Stare at the lights to judge distance","Look toward the RIGHT edge of your lane and slow down","Flash your brights back","Close one eye"],
    a:1, why:"Don't stare into oncoming lights — watch the right edge/lane line of your path and reduce speed until your vision recovers. Speed must always match what you can actually see." },
  { id:"sf06", cat:"safety", q:"Your car begins to SKID (rear slides out). The correct recovery is:",
    choices:["Slam the brakes and hold the wheel straight","Ease off the gas and steer GENTLY where you want to go","Accelerate hard","Yank the parking brake"],
    a:1, why:"In a skid, stay off the brake, ease off the gas, and steer smoothly toward your intended path ('steer into the skid' — turn the way the rear is sliding). Over-correcting causes snap spinouts." },
  { id:"sf07", cat:"safety", q:"Your BRAKES FAIL completely. The correct order of actions is:",
    choices:["Pump the brake pedal, downshift to a low gear, then apply the parking brake gradually","Immediately pull the parking brake at full speed","Turn off the engine","Steer into oncoming traffic to use their momentum"],
    a:0, why:"Pump for residual pressure, downshift to engine-brake, then feather the parking brake. Scrape against a curb or guardrail if needed and steer to a safe run-off. Turning the engine off kills power steering and can lock the wheel." },
  { id:"sf08", cat:"safety", q:"A TIRE BLOWS OUT at speed. You should:",
    choices:["Brake hard immediately","Grip the wheel firmly, ease off the gas, and slow gently before pulling off","Accelerate to stabilize the car","Swerve to the shoulder instantly"],
    a:1, why:"A blowout pulls the car hard to one side. Firm grip, foot off the gas, NO hard braking — let the car decelerate, then ease to the shoulder once slow. Braking hard with a blown front tire flips the car." },
  { id:"sf09", cat:"safety", q:"Your accelerator sticks open. First action:",
    choices:["Turn the key fully off","Shift to NEUTRAL and brake, then pull over and stop the engine","Brake with the parking brake at speed","Keep driving to a mechanic"],
    a:1, why:"Neutral disconnects the engine from the wheels — you keep steering and braking while the engine just revs. Then brake, pull off, and shut down. (Don't turn the key fully off at speed: it can lock the steering.)" },
  { id:"sf10", cat:"safety", q:"Your engine stalls while you're driving. You should:",
    choices:["Slam the brakes","Keep steering (it's harder without power), signal, brake gently, and coast to the side","Turn the wheel sharply","Stop in the travel lane immediately"],
    a:1, why:"Steering and brakes still work after a stall — just heavier. Grip firmly, signal, brake smoothly, and steer off the road, then restart with park/neutral. Warn traffic with hazards once stopped." },
  { id:"sf11", cat:"safety", q:"You're the first at a crash scene with possible injuries. The BEST first action is:",
    choices:["Move all injured people out of the cars immediately","Park safely, protect the scene (hazards/flares), call 911, and aid the injured unless moving them is necessary","Leave to find help","Give injured people water"],
    a:1, why:"Protect the scene so no secondary crash occurs, call emergency services, and check the injured. Don't move an injured person unless there's immediate danger (fire, traffic) — movement can worsen spinal injuries." },
  { id:"sf12", cat:"safety", q:"You hit an unattended parked car. You must:",
    choices:["Drive off if no one saw","Leave a note with your name, contact, and insurance info, and report as required by state law","Wait 10 minutes then leave","Pay cash to the nearest shop"],
    a:1, why:"Leaving without notice is hit-and-run — a criminal offense. Leave a visible note with your details (and photograph the damage), then notify police/DMV as your state requires." },
  { id:"sf13", cat:"safety", q:"Texting while driving:",
    choices:["Is safe at stoplights","Is illegal in almost every state and multiplies crash risk many times over","Is fine if you type quickly","Only matters for new drivers"],
    a:1, why:"Sending/reading a text takes your eyes off the road ~5 seconds — at 55 mph that's a football field driven blind. It's banned for all drivers in nearly all states, and it's a leading cause of teen crashes." },
  { id:"sf14", cat:"safety", q:"Large trucks have big blind spots ('no-zones'). The rule of thumb:",
    choices:["Trucks can see everything from their height","If you can't see the truck's MIRRORS, the driver can't see YOU","Trucks have no blind spots on the right","Following closely eliminates blind spots"],
    a:1, why:"Trucks have deep blind spots: up to 20 ft in front, 30 ft behind, and a full lane-width along the right side. If the truck's mirrors don't show you, assume you're invisible — pass promptly, never linger." },
  { id:"sf15", cat:"safety", q:"The area of your rearview mirrors that hides a motorcycle or small car is handled by:",
    choices:["Installing bigger mirrors","A head check (glance over the shoulder) before changing lanes","Slowing down before every lane change","Honking before changing lanes"],
    a:1, why:"Mirrors leave gaps where bikes hide completely. Signal, check mirrors, THEN glance over your shoulder into the blind spot before moving. 'SMOG': Signal, Mirrors, Over-shoulder, Go." },
  { id:"sf16", cat:"safety", q:"Motorcycles:",
    choices:["Can always stop faster than cars, so tailgating is fine","Need a full lane — never share a lane with one, and keep 3–4 seconds back","Must ride on the shoulder","Are only allowed in the left lane"],
    a:1, why:"Motorcycles are entitled to a full lane. Follow at 3–4+ seconds (they can brake very quickly), check blind spots carefully, and remember: 'looked but failed to see' causes most car-motorcycle crashes." },
  { id:"sf17", cat:"safety", q:"When an oncoming vehicle drifts into your lane at night, you should:",
    choices:["Move onto the shoulder at speed","Slow down, move right, honk and flash lights — don't swerve into their lane or off the road","Speed past on the left","Stop in your lane"],
    a:1, why:"Head-on space is precious: brake, hug the right, sound the horn and flash your lights. Never swerve LEFT into their path or off the pavement at speed unless impact is otherwise certain." },
  { id:"sf18", cat:"safety", q:"A child under about 8 years old should ride:",
    choices:["In the front seat with a belt","In an appropriate child seat or booster, in the BACK seat","On a parent's lap","In a booster in the front with the airbag on"],
    a:1, why:"Children need child seats/boosters matched to age, weight, and height — usually in the back seat until at least age 8–12 (when the adult belt fits correctly). Front seats with airbags are dangerous for young children." },
  { id:"sf19", cat:"safety", q:"Carbon monoxide from your car is dangerous because:",
    choices:["It smells strongly of fuel","It's odorless and colorless — never run an engine in a closed garage or idle in deep snow","It stains the windows","It only affects the driver"],
    a:1, why:"CO is invisible and scentless, causing drowsiness then death. Never warm a car in a closed garage, and if idling in deep snow, clear the exhaust pipe — blocked exhausts push CO into the cabin." },
  { id:"sf20", cat:"safety", q:"You feel drowsy on a long drive. The ONLY real fix is:",
    choices:["Loud music and fresh air","Coffee and a snack","Stop and rest (nap/lodge) — or switch drivers","Opening the window"],
    a:2, why:"Micro-sleeps happen no matter how alert you feel. Music, air, and caffeine only mask fatigue briefly. The safe choice is to stop — a 20-minute nap or a night's rest. Driving drowsy impairs like alcohol." },
  { id:"sf21", cat:"safety", q:"When being tailgated, the safest response is:",
    choices:["Brake-check them to send a message","Move right when safe and let them pass","Speed up beyond the limit","Turn on hazards and slow abruptly"],
    a:1, why:"Don't brake-check — that causes the very crash you fear. Increase YOUR following distance (so you can brake gently), then move over and let them by. You never win a road-rage contest; just disengage." },
  { id:"sf22", cat:"safety", q:"An angry driver antagonizes you (tailgating, gesturing). You should:",
    choices:["Respond so they don't think you're weak","Avoid eye contact, keep distance, and never follow or stop to confront","Speed away at 100 mph","Block them from passing"],
    a:1, why:"Disengage completely: distance, no eye contact, no gestures. If pursued, drive to a police station or busy public place — never home. Confrontations escalate unpredictably." },

  /* ================= RULES & PENALTIES ================= */
  { id:"lw01", cat:"laws", q:"When driving, you must carry:",
    choices:["Your license only — insurance stays at home","Your driver's license, and proof of registration and insurance in most states","Just a photo ID","Nothing, if you memorize your license number"],
    a:1, why:"Keep your license on you and the vehicle's registration and insurance proof in the car (paper or electronic where allowed). Failing to produce them at a stop brings fines — and driving uninsured can suspend your license." },
  { id:"lw02", cat:"laws", q:"You change your address. Most states require you to notify the DMV:",
    choices:["Never","Within days (commonly 10–30) of moving","Within 5 years","Only when you buy a new car"],
    a:1, why:"States require prompt address updates (often within 10–30 days) so licenses, notices, and recalls reach you. It's usually a quick online update — and tickets can follow missed notices." },
  { id:"lw03", cat:"laws", q:"You're in a crash causing injury or major damage. You must:",
    choices:["Stop, help the injured, exchange information, and report to police as required — leaving is a felony","Exchange info only if the other driver asks","Move on and report next week","Pay cash and leave"],
    a:0, why:"You MUST stop (leaving = hit-and-run), render aid, exchange license/insurance details, and report crashes with injury or over the damage threshold to police/DMV. Serious-injury hit-and-runs are felonies." },
  { id:"lw04", cat:"laws", q:"Unless a sign prohibits it, you may turn right on red:",
    choices:["After slowing to 10 mph","After a COMPLETE stop and yielding to pedestrians and cross traffic","Any time, without stopping","Only between 9 a.m. and 5 p.m."],
    a:1, why:"Right-on-red (where allowed) still requires a full stop at the line, then yielding to pedestrians and oncoming left-turners. Rolling turns on red are a common — and heavily enforced — ticket." },
  { id:"lw05", cat:"laws", q:"You must signal before turning or changing lanes:",
    choices:["Only if other cars are nearby","Continuously for at least the last 100 feet (more on highways)","After you begin the turn","Only when a police car is visible"],
    a:1, why:"Signal at least 100 feet before turning (300+ feet on fast roads) so others can react. Signaling after braking, or not at all, is both a citation and a crash cause." },
  { id:"lw06", cat:"laws", q:"Where is a U-turn generally ILLEGAL?",
    choices:["On any residential street","Near a curve or hill crest where you can't be seen 200 feet ahead, or where signs prohibit it","At any stop sign","In every intersection"],
    a:1, why:"U-turns are illegal where visibility is blocked (curves, crests), in business districts (unless at an intersection), across double yellow lines, and wherever posted. Otherwise they're legal if safely completed." },
  { id:"lw07", cat:"laws", q:"Crossing a SOLID white line means:",
    choices:["Crossing is prohibited (or discouraged) — e.g., lane exits or intersections","Crossing is always fine","It marks a bike lane's start","It's a pedestrian line"],
    a:0, why:"Solid white lines separate lanes where lane changes are prohibited or discouraged (like exit-only gore areas, intersections). Broken white lines = lane changes permitted." },
  { id:"lw08", cat:"laws", q:"Reckless driving is defined as:",
    choices:["Driving 1 mph over the limit","Driving with willful disregard for the safety of persons or property","Any lane change without a signal","Playing music loudly"],
    a:1, why:"Reckless driving — willful disregard for safety (extreme speed, weaving, racing, road-rage maneuvers) — is a serious misdemeanor, often with jail time, and can be charged even without a crash." },
  { id:"lw09", cat:"laws", q:"Accumulating too many points on your license typically leads to:",
    choices:["Nothing — points are just statistics","Warnings, then suspension/revocation of your license","Cheaper insurance","Automatic vehicle impound"],
    a:1, why:"Moving violations add points; enough points in a set period triggers progressive penalties ending in suspension or revocation. Points also raise insurance premiums for years." },
  { id:"lw10", cat:"laws", q:"HOV (diamond) lanes may be used by:",
    choices:["Any car at night","Vehicles carrying the posted minimum number of occupants (motorcycles often excepted)","Electric cars, always, everywhere","Trucks with 2+ axles"],
    a:1, why:"High-Occupancy Vehicle lanes require the posted minimum headcount (usually 2–3) during designated hours. Motorcycles are typically exempt; EVs/placards only where signed. Violations draw big fines." },
  { id:"lw11", cat:"laws", q:"A police officer signals you to pull over. You should:",
    choices:["Stop instantly in the travel lane","Signal, slow, and pull completely off the road to the right, then stay in the car with hands visible","Get out and walk back to the officer","Keep driving until you feel like it"],
    a:1, why:"Signal, ease right fully off the roadway, stop, roll the window down, keep hands on the wheel, and stay in the car unless directed. At night, turn on the dome light. Sudden movements put officers on alert." },
  { id:"lw12", cat:"laws", q:"If your license is SUSPENDED or revoked, you:",
    choices:["May drive to work only","May not drive at all until reinstated","May drive with a friend in the car","May drive during daylight"],
    a:1, why:"No driving, period — driving on a suspended/revoked license is a new offense with jail time and extensions. Reinstate first (fees, hearings, sometimes an ignition interlock)." },
  { id:"lw13", cat:"laws", q:"Littering from a vehicle:",
    choices:["Is harmless for organic waste","Carries fines (often escalated for highway litter), and unsecured loads are illegal","Is legal on rural roads","Only applies to cigarettes"],
    a:1, why:"Littering fines are steep (many states escalate for highway litter), and a cigarette tossed roadside can spark wildfires. Loads must be secured — flying debris causes real crashes and real felony charges." },
  { id:"lw14", cat:"laws", q:"Wearing headphones or earbuds in BOTH ears while driving:",
    choices:["Is safe if the volume is low","Is illegal in most states — you must be able to hear sirens, horns, and trains","Is required for hands-free calls","Is only illegal for truckers"],
    a:1, why:"Most states ban covering both ears — you need to hear emergency vehicles, horns, and crossing bells. A single earpiece for calls is the common allowance." },
  { id:"lw15", cat:"laws", q:"Using your phone's GPS while driving:",
    choices:["Is always illegal","Is fine if programmed before you drive; programming it while moving can be cited as distracted driving","Is legal at any speed","Is only legal on highways"],
    a:1, why:"Set your destination before moving (or while parked). Touching and programming a device in traffic falls under handheld and distracted-driving laws in most states." },

  /* ================= SIGNS: additional visual questions ================= */
  { id:"sg36", cat:"signs", signId:"hill", q:"This sign warns of:",
    choices:["A truck stop ahead","A steep downgrade — slow down and use a low gear","A rest area ahead","A weigh station ahead"],
    a:1, why:"The truck-on-grade sign marks a steep hill. Slow BEFORE the crest and shift to a low gear so engine braking holds your speed — riding the brakes downhill overheats them (brake fade)." },
  { id:"sg37", cat:"signs", signId:"deadEnd", q:"This sign means:",
    choices:["Detour ahead","The road ahead ends — it doesn't connect through","No outlet for trucks","Lane ends, merge left"],
    a:1, why:"DEAD END means the road terminates without a through connection. Start slowing early and plan your turn-around — don't brake at the last second." },
  { id:"sg38", cat:"signs", signId:"softShoulder", q:"This sign means:",
    choices:["Construction ahead","The shoulder is soft (dirt or gravel) — unsafe at speed","A steep drop-off","No parking on the grass"],
    a:1, why:"A soft shoulder can't support a car at speed — wheels sink and drag you off the road. If you must use it, slow down first, grip the wheel, and return to pavement gently." },
  { id:"sg39", cat:"signs", signId:"noLeftTurn", q:"This sign means:",
    choices:["No left turns here","Left turns are prohibited — plan an alternate route","Detour to the left","The left lane ends"],
    a:1, why:"A slashed left-turn arrow prohibits left turns at that location. Continue and loop around (three rights make a left) instead of risking an illegal turn." },
  { id:"sg40", cat:"signs", signId:"schoolCrossing", q:"How is a SCHOOL CROSSING sign different from a SCHOOL ZONE sign?",
    choices:["It's blue instead of yellow-green","It marks where children actually cross — slow down and prepare to stop","It applies only to buses","It means the school is closed"],
    a:1, why:"The pentagon with children on a crosswalk marks the crossing itself; the walking-figures pentagon warns of the school zone ahead. Never pass cars stopped there — children cross mid-block." },

  /* ================= RIGHT OF WAY: additions ================= */
  { id:"rw20", cat:"row", q:"Turning LEFT on red (from a one-way street onto a one-way street) is:",
    choices:["Illegal everywhere","Legal in many states unless a sign prohibits it — after a full stop and yielding to everything","Legal only during daylight","Legal only for trucks"],
    a:1, why:"Many states allow left-on-red from one one-way onto another, with the same rules as right-on-red: complete stop, yield to traffic and pedestrians. A prohibiting sign always wins." },
  { id:"rw21", cat:"row", q:"You're turning right at a green light while pedestrians cross your target street. You must:",
    choices:["Turn quickly behind them","Wait until they clear your half of the crosswalk (or fully cross, per your state)","Honk so they hurry","Ease into the crosswalk"],
    a:1, why:"Turning traffic yields to pedestrians — even on green. Wait behind the line until they're clear; squeezing past at speed is exactly how 'right-hook' collisions happen." },

  /* ================= SPEED & DISTANCE: additions ================= */
  { id:"sp15", cat:"speed", q:"Total stopping distance is made up of:",
    choices:["Braking distance only","Perception distance + reaction distance + braking distance","Reaction distance only","Two car lengths, always"],
    a:1, why:"You travel while you SEE the hazard, while you REACT (~1 second ≈ 80 feet at 55 mph), and while the car BRAKES. At 55 mph the total is longer than a football field." },
  { id:"sp16", cat:"speed", q:"A following distance of 2 seconds is:",
    choices:["Enough in all conditions","Only a floor for perfect conditions — use 3+ seconds, and double it in rain, night, or behind trucks","The legal maximum","For experienced drivers only"],
    a:1, why:"Two seconds is the bare minimum in ideal conditions. Most handbooks teach 3 seconds, adding more for rain (4s), night, and snow or ice (6s+), and whenever following motorcycles and trucks." },

  /* ================= ALCOHOL: additions ================= */
  { id:"al12", cat:"alcohol", q:"Which factors actually determine your blood alcohol content (BAC)?",
    choices:["Willpower and confidence","Number of drinks, rate of drinking, body weight, food, and time","Coffee consumed","The kind of music playing"],
    a:1, why:"BAC rises with how much and how fast you drink, and falls only with time — roughly one standard drink processed per hour. Body weight and food change your peak; nothing but time lowers it." },
  { id:"al13", cat:"alcohol", q:"Repeat DUI offenders are commonly required to install:",
    choices:["A speed limiter","An ignition interlock — a breath test the car must pass before starting","A louder horn","Special license plates only"],
    a:1, why:"Ignition interlocks are standard for repeat (and increasingly first) DUI offenses, alongside license restrictions, mandatory classes, and fines. Tampering with one is a new offense." },

  /* ================= SAFETY: additions ================= */
  { id:"sf23", cat:"safety", q:"A deer runs onto the road directly ahead. Generally you should:",
    choices:["Swerve hard into the next lane","Brake firmly and stay in your lane — don't swerve at speed unless hitting a person is the alternative","Accelerate to get past it","Turn off your headlights"],
    a:1, why:"Brake hard in a straight line and sound the horn. Swerving at speed often causes a worse rollover or head-on crash. If hitting the animal is unavoidable, hold your lane and brake." },
  { id:"sf24", cat:"safety", q:"After a collision you must exchange:",
    choices:["Only first names","Driver's license, contact and insurance details, and vehicle/plate information — plus help any injured people","A handshake and apology","Nothing if the other driver leaves first"],
    a:1, why:"Exchange name, address, license number, insurance, and plate/vehicle details; render aid to the injured; and report as your state requires. Leaving without exchanging is hit-and-run." },

  /* ================= ROAD MARKINGS & LANES ================= */
  { id:"mk01", cat:"markings", q:"A BROKEN (dashed) yellow line beside the centerline on your side means:",
    choices:["Passing is prohibited","You may pass when it's safe","The road is one-way","An emergency lane is ahead"],
    a:1, why:"On two-way roads, a broken yellow line on your side means passing is allowed when the way ahead is clear. A solid yellow on your side means passing is prohibited." },
  { id:"mk02", cat:"markings", q:"DOUBLE solid yellow centerlines mean:",
    choices:["Passing allowed from both directions","No passing from either direction — cross only to turn left where permitted","A railroad crossing ahead","A reversible lane"],
    a:1, why:"Double solid yellow lines prohibit passing in either direction. In most states you may cross them only to turn left into a driveway or side road where legal — never to pass." },
  { id:"mk03", cat:"markings", q:"A SOLID white line between lanes means:",
    choices:["Lane changes are permitted","Lane changes are discouraged or prohibited — stay in your lane","The lane is ending","It marks a bike lane only"],
    a:1, why:"Solid white lines separate lanes where changing is prohibited or discouraged — near intersections, exits, and gore areas. Broken white lines mean lane changes are allowed when safe." },
  { id:"mk04", cat:"markings", q:"What's the difference between YELLOW and WHITE pavement lines?",
    choices:["Yellow separates same-direction traffic; white separates opposing","Yellow separates OPPOSING traffic (and marks the left edge); white separates same-direction traffic","White is only used in construction zones","There is no difference"],
    a:1, why:"Yellow lines divide traffic moving in opposite directions and mark the left edge of a one-way road; white lines divide traffic moving the same direction. A yellow edge line is always on your LEFT." },
  { id:"mk05", cat:"markings", q:"A center lane bounded by a broken yellow line inside a solid yellow line (on both sides) is:",
    choices:["A passing lane","A shared two-way LEFT TURN lane","An HOV lane","A truck lane"],
    a:1, why:"That's a center two-way left-turn lane: used by traffic from BOTH directions to prepare left turns (usually limited to ~200–400 feet). Never use it for passing or through travel." },
  { id:"mk06", cat:"markings", q:"A bike lane (bicycle symbol + solid white line) may be driven in:",
    choices:["Whenever traffic is heavy","Only where permitted for turning — after yielding to riders; never for passing or parking","For up to 500 feet at any time","If you travel under 25 mph"],
    a:1, why:"Bike lanes are for bicycles. Cars enter only where signs or markings permit (typically to turn right near an intersection, after yielding to cyclists). Driving or parking in them is illegal." },
  { id:"mk07", cat:"markings", q:"Two parallel white lines crossing the road (or zebra bars) mark:",
    choices:["A speed table","A pedestrian crosswalk — yield and never block it","A railroad crossing","A stop line"],
    a:1, why:"Parallel or zebra lines mark a crosswalk. Pedestrians have the right of way there — stop behind the stop line, and never block the crosswalk even in heavy traffic." },
  { id:"mk08", cat:"markings", q:"The thick solid white line before an intersection shows:",
    choices:["Where to stop — stop fully BEFORE it","Where pedestrians must wait","A merge point","A no-parking zone"],
    a:0, why:"The thick white stop line marks where you must stop for signals and signs — behind the line, before the crosswalk, and before entering the intersection." },
  { id:"mk09", cat:"markings", q:"A painted DIAMOND on the pavement marks:",
    choices:["A toll lane","A restricted HOV (high-occupancy vehicle) lane","A hazard area","A truck climbing lane"],
    a:1, why:"The diamond marks HOV lanes, restricted during posted hours to vehicles carrying the minimum posted occupancy (motorcycles and transit are often exempt). Violations draw steep fines." },
  { id:"mk10", cat:"markings", q:"The diagonally striped area between a through lane and an exit or merge lane (the 'gore') is:",
    choices:["A breakdown lane","Never to be driven in — it's a neutral island between merging paths","A passing zone","An acceleration lane"],
    a:1, why:"Gore areas separate merging and diverging lanes. Crossing them — especially a last-second dive to make an exit — is dangerous and illegal. Miss the exit; take the next one." },
  { id:"mk11", cat:"markings", q:"At a railroad crossing, a crossbuck with a plaque reading '2' means:",
    choices:["A 2 mph zone","Two tracks — after one train passes, a second may be hidden behind it","Two-way traffic","A 2-hour parking limit"],
    a:1, why:"The plaque shows the number of tracks. Never start across until you can see along ALL tracks — a second train can be hidden behind the first, in either direction." },
  { id:"mk12", cat:"markings", q:"A white arrow painted in your lane pointing left means:",
    choices:["Left turns are suggested","You must turn left from that lane","Detour ahead","Trucks only"],
    a:1, why:"Pavement arrows control lane use: a straight arrow must go straight, a left arrow must turn left. Pick the right lane BEFORE you enter the intersection." },
  { id:"mk13", cat:"markings", q:"When is passing on the RIGHT legal?",
    choices:["Never","On roads with multiple same-direction lanes, or when the vehicle ahead is turning left — never via the shoulder","Only on one-way streets","Only in daylight"],
    a:1, why:"Passing on the right is legal on multi-lane roads and when the car ahead signals a left turn — done in a proper travel lane. Passing on the shoulder is always illegal." },
  { id:"mk14", cat:"markings", q:"RED raised reflective pavement markers facing you mean:",
    choices:["A fire hydrant is nearby","You're on the wrong side or going against traffic — pull off safely and turn around","A snow-chain area","A toll plaza ahead"],
    a:1, why:"Red reflectors are aimed at wrong-way drivers — seeing them usually means you're against traffic (often on a ramp). Yellow markers sit on the left and centerline, white on lane lines, blue marks hydrants." },
  { id:"mk15", cat:"markings", q:"Your lane ends ahead (converging lines / 'LANE ENDS' sign). You should:",
    choices:["Speed up to get ahead of traffic","Merge early when safe — and alternate one car each (zipper) in heavy traffic","Stop at the end of the lane","Straddle both lanes until someone lets you in"],
    a:1, why:"Merge smoothly before the lane runs out. In congestion, alternating at the taper ('zipper merge') keeps traffic moving and prevents last-second cutoffs." },

  /* ================= PEDESTRIANS, BIKES & MOTORCYCLES ================= */
  { id:"vr01", cat:"vulnerable", q:"When passing a bicyclist, most states require at least:",
    choices:["1 foot of clearance","3 feet of clearance","Half a lane is enough","6 inches"],
    a:1, why:"Most states set a 3-foot minimum when passing bicycles (some require more). Slow down, move over fully when possible, and never squeeze past — wind pressure alone can unseat a rider." },
  { id:"vr02", cat:"vulnerable", q:"A cyclist hugging the right edge suddenly swerves LEFT toward your lane. Most likely:",
    choices:["They're turning around","They're avoiding a hazard — debris, a drain, or a parked car's opening door","They're challenging you","They lost control"],
    a:1, why:"Riders swerve for hazards drivers never see: gravel, potholes, grates, and the 'door zone' beside parked cars. Expect it, ease off the gas, and pass only with real clearance." },
  { id:"vr03", cat:"vulnerable", q:"A group of cyclists rides ahead of you. You should:",
    choices:["Honk so they single up","Pass only when legal, with clear sight distance and room for the WHOLE group — like any slow vehicle","Squeeze between them and oncoming traffic","Tailgate until they move over"],
    a:1, why:"Treat a cycling group as one slow vehicle. Wait for a legal passing zone with room to clear every rider — threading between riders and oncoming traffic is a common fatal mistake." },
  { id:"vr04", cat:"vulnerable", q:"Two motorcyclists ride side by side in one lane. This means:",
    choices:["You may share their lane too","You must NEVER ride alongside them — a motorcycle owns its full lane","That lane is twice as wide","It's illegal for them"],
    a:1, why:"Riders may share a lane with each other, but motor vehicles may never share or 'split' a motorcycle's lane. Change lanes fully to pass — never crowd alongside." },
  { id:"vr05", cat:"vulnerable", q:"A motorcyclist shifts position within their lane as you approach an intersection. Usually they're:",
    choices:["Showing off","Making themselves visible and avoiding blind spots — look twice before turning","Preparing to race","Signaling you to pass"],
    a:1, why:"Riders move within the lane to be seen and to avoid oil, grease, and blind spots. Before turning across traffic, look TWICE — 'looked but failed to see' causes most car-motorcycle crashes." },
  { id:"vr06", cat:"vulnerable", q:"A motorcycle's turn signal has been blinking for a long stretch. You should:",
    choices:["Assume they'll turn and pull out","Wait — many motorcycle signals don't cancel automatically; watch their head and body instead","Honk to remind them","Ignore all motorcycle signals"],
    a:1, why:"Unlike cars, most motorcycle turn signals don't shut off on their own. A blinking signal doesn't guarantee a turn — read the rider's head checks and lean before acting." },
  { id:"vr07", cat:"vulnerable", q:"Why do so many drivers say they 'never saw' the motorcycle they hit?",
    choices:["Motorcycles are usually speeding","Their narrow profile hides in blind spots and blends into the background — scan intersections twice","Motorcycles have no lights","They always lane-split"],
    a:1, why:"Motorcycles are small and easily lost in glare, blind spots, and background clutter — especially at intersections, where most collisions happen. Train your eyes to spot two wheels and a helmet, not just car shapes." },
  { id:"vr08", cat:"vulnerable", q:"A pedestrian crosses mid-block, against the signal, into your path. You should:",
    choices:["Maintain speed — you have the right of way","Slow and yield — right of way never justifies a collision","Honk and keep going","Swerve into oncoming traffic"],
    a:1, why:"Right of way is something you YIELD, not enforce. Whoever is wrong, the person on foot loses every collision — slow, cover the brake, and give them the road." },
  { id:"vr09", cat:"vulnerable", q:"A ball rolls into the street ahead of you. You should:",
    choices:["Maintain speed — it's just a ball","Slow immediately and cover the brake — expect a child to chase it","Honk to warn","Swerve around it at speed"],
    a:1, why:"A rolling ball is often a child a half-second behind it. In residential areas, expect kids to dart from between parked cars without looking — slow down and be ready to stop." },
  { id:"vr10", cat:"vulnerable", q:"An elderly pedestrian is still crossing when your light turns green. You should:",
    choices:["Edge forward to hurry them along","Wait calmly until they finish — some people need more time","Honk lightly","Drive around behind them"],
    a:1, why:"Give every pedestrian the time they need — especially elderly or disabled people using canes and walkers. Never nudge, rev, or honk at someone in a crosswalk." },
  { id:"vr11", cat:"vulnerable", q:"A crossing guard holds up a STOP paddle, but the traffic signal is green. You must:",
    choices:["Obey the signal only","Obey the guard — their directions override signals and signs","Obey whichever lets you proceed","Stop only if children are visible"],
    a:1, why:"Crossing guards direct traffic by legal authority, like flaggers and police: their STOP paddle overrides the signal. Stay stopped until the guard lowers it and clears the crossing." },
  { id:"vr12", cat:"vulnerable", q:"An e-scooter or e-bike rider is using the bike lane. Treat them:",
    choices:["As a pedestrian","Like a bicycle — same rights, same lane, same passing clearance","As a motorcycle","As a parked object"],
    a:1, why:"In most states e-scooters and e-bikes are legally bicycles: same road rights, same lanes, same 3-foot passing rule. Their riders are less visible and less protected — give extra space." },
  { id:"vr13", cat:"vulnerable", q:"You approach a horse and rider on a rural road. You should:",
    choices:["Pass quickly to get past","Slow down and pass wide and quiet — no horn, no revving","Honk so the horse knows you're there","Follow closely until they turn off"],
    a:1, why:"Horses are flight animals — a horn or a fast pass can panic them and throw the rider. Many states require slowing, a wide berth, or stopping. Pass gently and give the whole lane if you can." },
  { id:"vr14", cat:"vulnerable", q:"Driving beside a row of parked cars in the city, the safest habit is:",
    choices:["Hug the curb to let others pass","Slow slightly and leave a door-width gap — doors open without warning","Watch only the traffic ahead","Keep your high beams on"],
    a:1, why:"The 'door zone' beside parked cars is a constant trap: watch for people inside, reverse lights, and turned front wheels — each predicts a door or a car pulling out. A little space prevents the crash." },

  /* ================= VEHICLE BASICS & MAINTENANCE ================= */
  { id:"vh01", cat:"vehicle", q:"When should you adjust your seat, mirrors, and steering wheel?",
    choices:["While driving, to save time","Before starting the engine — along with fastening your belt","Only in rental cars","After the first mile"],
    a:1, why:"Set your driving position before you move. Fiddling with mirrors at speed takes your eyes off the road, and a bad seat position slows pedal control in emergencies." },
  { id:"vh02", cat:"vehicle", q:"Can correctly adjusted mirrors eliminate blind spots?",
    choices:["Yes, especially convex mirrors","No — always glance over your shoulder before changing lanes","Yes, on new cars","Only at low speeds"],
    a:1, why:"Mirrors minimize but never eliminate blind spots. Signal, check mirrors, then a quick over-the-shoulder check (SMOG: Signal, Mirrors, Over-shoulder, Go) catches what mirrors hide — especially motorcycles." },
  { id:"vh03", cat:"vehicle", q:"Your car has ABS and you must brake HARD in an emergency. You should:",
    choices:["Pump the brake pedal rapidly","Press hard and KEEP steering — a pulsing pedal is the system working normally","Pull the parking brake","Switch the engine off"],
    a:1, why:"With ABS: stomp, stay, steer. Press the pedal hard and steer around the hazard — the vibration and grinding noise mean ABS is preventing lockup. Pumping defeats the system." },
  { id:"vh04", cat:"vehicle", q:"Where do you find the correct tire pressure for YOUR car?",
    choices:["On the tire's sidewall","On the sticker in the driver's door jamb (or in the owner's manual)","At 32 psi for every car","On the windshield"],
    a:1, why:"The door-jamb placard lists the manufacturer's recommended pressures. The sidewall number is the tire's MAXIMUM pressure, not your car's setting. Check monthly, cold, including the spare." },
  { id:"vh05", cat:"vehicle", q:"The 'penny test' checks:",
    choices:["Brake pad wear","Tire tread depth — if you can see all of Lincoln's head, replace the tire","Oil level","Battery charge"],
    a:1, why:"Insert a penny head-down into the groove: seeing all of Lincoln's head means the tread is at or below 2/32 of an inch — legally worn out in most states. Worn tires hydroplane and blow out; many experts replace at 4/32." },
  { id:"vh06", cat:"vehicle", q:"Your brake pedal suddenly feels spongy or sinks toward the floor. You should:",
    choices:["Pump it and keep driving carefully","Get the car towed or serviced before driving — the hydraulic system may be failing","Ignore it if the warning light is off","Top up any fluid and forget it"],
    a:1, why:"A soft or sinking pedal suggests a leak or air in the brake hydraulics — the brakes can fail completely without further warning. Don't drive it; have it serviced or towed." },
  { id:"vh07", cat:"vehicle", q:"The horn should be used:",
    choices:["To greet friends and family","To warn others of immediate danger","To urge slower drivers to move over","Whenever you feel frustrated"],
    a:1, why:"Horns exist to prevent collisions — warn a driver drifting into your lane or a pedestrian stepping off a curb. Social or angry honking is illegal in many places and fuels road rage." },
  { id:"vh08", cat:"vehicle", q:"On a frosty morning you must clear:",
    choices:["A peephole on the driver's side","ALL windows, mirrors, and lights — full visibility before moving","Only the windshield, while driving","Whatever the wipers reach"],
    a:1, why:"Driving with blocked windows is illegal and dangerous — you can't check mirrors or blind spots through frost. Scrape everything and let the defroster finish while you buckle up." },
  { id:"vh09", cat:"vehicle", q:"Loose items inside the passenger compartment:",
    choices:["Are fine on the rear shelf","Must be secured — in a crash they strike with many times their weight","Only matter in trucks","Are stopped by the airbag"],
    a:1, why:"In a crash, loose objects keep moving at your pre-crash speed — a phone or water bottle becomes a missile. Use the glovebox and cargo areas, and never place items on the rear shelf or your lap." },
  { id:"vh10", cat:"vehicle", q:"A backup camera should be used:",
    choices:["Instead of turning your head","As an aid — still check mirrors and physically look behind before reversing","Only at night","Only when parking downhill"],
    a:1, why:"Cameras have blind zones at the edges and rear corners and can be blocked by dirt or glare. Use them WITH mirrors and a look back — children and pets hide in every system's gaps." },
  { id:"vh11", cat:"vehicle", q:"The recommended hand position on the steering wheel is:",
    choices:["12 o'clock only","9 and 3 — balanced control and clear of the airbag's path","10 and 2, always","One hand at the bottom, relaxed"],
    a:1, why:"9-and-3 gives smooth, balanced steering and keeps your forearms out of the airbag's deployment path (the older 10-and-2 puts them across it). Turn with push-pull steering rather than crossing hands." },
  { id:"vh12", cat:"vehicle", q:"Stopped facing uphill in traffic, you should:",
    choices:["Hold the car on the throttle","Hold the brake until you move — and keep extra space behind the car ahead in case you roll back","Roll back a little on purpose","Use the parking brake only, always"],
    a:1, why:"Keep your foot on the brake until you're ready to move (or use the handbrake for a manual hill start). A full gap behind you forgives a small roll-back and prevents bumping the car behind." },
  { id:"vh13", cat:"vehicle", q:"Why keep at least a quarter tank of fuel?",
    choices:["Fuel is cheaper in bulk","Running dry strands you in emergencies — and a near-empty tank pulls sediment and condensation through the fuel system","The gauge is inaccurate below a quarter","It's required by law"],
    a:1, why:"A quarter tank is your buffer for detours, winter storms, and emergencies. Regularly running on fumes also feeds the pump sediment and tank condensation — a classic breakdown cause." },
  { id:"vh14", cat:"vehicle", q:"Your wipers smear and streak in rain. You should:",
    choices:["Drive faster to shed the water","Replace the blades before your next trip — worn blades destroy visibility at speed","Rely on washer fluid only","Turn on your hazards"],
    a:1, why:"Streaking blades smear oncoming headlights into glare exactly when you need clear vision. Wipers are cheap and take minutes to swap — replace at the first smear, usually every 6–12 months." },
  { id:"vh15", cat:"vehicle", q:"One headlight has burned out. You should:",
    choices:["Drive with high beams instead","Replace it promptly — with one light, oncoming drivers misjudge you as a far-away motorcycle","Wait until both fail","Use hazards at night"],
    a:1, why:"A single headlight makes you look like a distant motorcycle, so oncoming drivers pull out or turn across you. Replace bulbs promptly and carry a spare — driving with one is illegal." },

  /* ================= QUESTION-FORM DIVERSITY =================
     Scenes (ASCII road layouts), sign combinations, lane selection,
     what-happens-next and prioritisation items. Same universal rules as
     above, tested as situations instead of definitions. */

  { id:"rw22", cat:"row", form:"scenario", scene:"          YOU\n           ↓\n     ──────┼─────\n CAR →   │   BUS ↓\n         │\n    pedestrian",
    concept:"junction-priority",
    q:"You are leaving a parking lot (bottom road) onto the through street. Who must yield?",
    choices:["You — to the car and the bus on the through road","The car, because you are turning","The bus, because it is heaviest","Whoever arrived last"],
    a:0,
    why:"When entering from a driveway, lot or side road you yield to ALL traffic on the through road — vehicle type and arrival order never create priority. Wait for gaps in both directions plus the pedestrian on your path.",
    sourceId:"us-dmv-handbooks-composite" },
  { id:"rw23", cat:"row", form:"scenario", scene:"      ← CAR A\n   ┌────────┐\n   │ round- │\n   │ about  │\n   └────────┘\n   YOU ↑ (right-hand lane)",
    concept:"junction-priority",
    q:"You approach this roundabout in the right-hand lane intending the first exit. What is required?",
    choices:["Yield to traffic already circulating from the left, then exit without signalling early","Stop completely even when the circle is clear","Enter alongside the car to your left","Signal left before entering"],
    a:0,
    why:"At roundabouts you yield to circulating traffic (it comes from your left where you drive on the right) and never enter beside another vehicle. Signal RIGHT for your first exit after passing the one before it.",
    sourceId:"us-dmv-handbooks-composite" },
  { id:"rw24", cat:"row", form:"what-next", scene:"   YOU ↓ (green light)\n        ║╲\n        ║ ╲  oncoming\n   ▓▓▓▓▓║▓▓╲▓▓▓\n    PEDESTRIAN crossing with walk signal",
    concept:"turn-priority",
    q:"Your light is green and you're turning left across the intersection. The pedestrian crossing has a WALK signal. What happens next?",
    choices:["You complete the turn — green means go","You yield and wait until the pedestrian clears, even if your light turns red","Honk so they hurry","Turn behind them closely"],
    a:1,
    why:"A green light gives permission to ENTER the intersection, not to cross conflicting paths: left-turners yield to oncoming traffic AND pedestrians lawfully in the crosswalk. If your light turns red while they finish, stay put until they clear.",
    sourceId:"us-dmv-handbooks-composite" },
  { id:"mk16", cat:"markings", form:"lane-choice", scene:"  ║   ║   ║\n  ║ ↰ ║ ↑ ║\n  ╚═══╩═══╝\n   L1  L2  L3   YOU ↑\n   (L1 turn-only arrow, L2 straight arrow, L3 plain)",
    concept:"lane-selection",
    q:"You want to go STRAIGHT through this junction and there's traffic ahead. Which lane may you use?",
    choices:["Only L2 — the straight-arrow lane","L2 or L3 — plain lines allow any movement; arrows lock a lane to its marking","Any lane including L1","Only L3"],
    a:1,
    why:"Arrows painted in a lane confine you to that movement; a lane with only line markings keeps all legal movements. So straight traffic belongs in L2, or L3 if its plain markings allow it — never the turn-only lane.",
    sourceId:"us-dmv-handbooks-composite" },
  { id:"mk17", cat:"markings", form:"lane-choice", scene:"  → →  ═══════╗\n              ║ EXIT\n  ← ←  ═══════╝\n  YOUR LANE → approaching gore stripes ▨▨▨",
    concept:"lane-selection",
    q:"You've missed your exit and you're beside the striped gore area. What now?",
    choices:["Cut across the stripes quickly","Continue and take the next exit — diagonal stripes mark an area you must never drive through","Back up along the shoulder","Stop and reverse onto the exit ramp"],
    a:1,
    why: "Diagonal-striped (gore) areas separate traffic streams at exits — driving over or stopping in them causes merge crashes, and reversing on a highway is always prohibited. Miss it? Own the miss: next exit.",
    sourceId:"us-dmv-handbooks-composite" },
  { id:"sg41", cat:"signs", form:"sign-combo", signIds:["stop","noUturn"], form:"sign-combo",
    q:"These two signs hang together at an intersection. Combined, they tell you:",
    choices:["Stop, then U-turn if safe","Stop — and note that U-turns are banned here entirely","U-turn allowed after stopping","Yield instead of stopping"],
    a:1,
    why:"Signs apply together: come to a FULL stop as always, and do not attempt a U-turn at this location — the prohibition holds even though a stop gives you time to check.",
    sourceId:"us-dmv-handbooks-composite" },
  { id:"sg42", cat:"signs", form:"sign-combo", signIds:["oneWay","doNotEnter"], form:"sign-combo",
    q:"You meet these signs facing opposite directions at either end of a street. The pair means:",
    choices:["Two-way street ahead","ONE WAY — entering against the Do-Not-Enter face would put you head-on into traffic","Street closed permanently","Trucks only"],
    a:1,
    why:"ONE WAY marks the permitted direction while DO NOT ENTRY faces drivers coming the forbidden way. If you can read DO NOT ENTER facing you, you are already going the wrong way — turn around safely immediately.",
    sourceId:"us-dmv-handbooks-composite" },
  { id:"sf25", cat:"safety", form:"what-next", concept:"following-distance",
    q:"The car ahead passes a mailbox. You count 'one-thousand-one' and reach it. What happens next if they brake hard?",
    choices:["You stop in time comfortably","You likely hit them — at 55 mph one second is roughly 80 feet of travel before braking even starts","Nothing — brakes work instantly","Swerving is automatically safer"],
    a:1,
    why:"Perception plus reaction eats up about one second (~80 feet at 55 mph) BEFORE braking begins. A one-second gap guarantees rear-ending; use three-plus seconds and add more in rain or night.",
    sourceId:"us-dmv-handbooks-composite" },
  { id:"sf26", cat:"safety", form:"scenario", concept:"skid-recovery",
    q:"Mid-corner your rear wheels start sliding outward (oversteer). Sequence the recovery:",
    choices:["Brake hard and steer straight","Ease off gas, steer smoothly WHERE YOU WANT TO GO, avoid braking until grip returns","Accelerate to spin out of it","Pull the handbrake"],
    a:1,
    why:"In a skid, abrupt inputs make it worse: lift off the gas gently and look/steer toward your intended path — the car follows your eyes. Hard braking transfers weight violently and prolongs the slide.",
    sourceId:"us-dmv-handbooks-composite" },
  { id:"vr15", cat:"vulnerable", form:"scenario", scene:"  SIDEWALK ▓▓▓│▓▓▓\n               │← pedestrian waiting, no marked crosswalk anywhere\n  YOU → (through street)",
    concept:"pedestrian-priority",
    q:"A pedestrian waits at the sidewalk where there is NO crosswalk. You're on the through road. What's the safest legal read?",
    choices:["Pedestrians may not cross — continue at speed","Slow and be ready to yield — pedestrians crossing between intersections must still be given room, and predictability protects everyone","Speed up past the point","Honk to clear the way"],
    a:1,
    why:"Outside marked crossings, pedestrians who step out must generally yield to vehicles — but drivers must exercise due care, slow when visibility is limited, and give them space once they are crossing. Expecting the unexpected is defensive driving.",
    sourceId:"us-dmv-handbooks-composite" },
  { id:"vr16", cat:"vulnerable", form:"prioritisation", concept:"pedestrian-priority",
    q:"Simultaneously: a cyclist wobbles ahead of you, a pedestrian steps off the curb ahead-right, and an oncoming car drifts over the centerline. Rank your response:",
    choices:["Cyclist first — nearest hazard wins","Manage speed and position to create ONE escape buffer covering all three, then address each in order of immediacy","Oncoming car first because it is heaviest","Sound horn continuously and brake late"],
    a:1,
    why:"Good drivers don't pick one hazard — they manage SPACE so every threat has an answer: ease off, add following distance, move within your lane away from the drift. Then handle the most immediate conflict first with room still available.",
    sourceId:"us-dmv-handbooks-composite" },
  { id:"lw17", cat:"laws", form:"recall", concept:"emergency-vehicles",
    q:"An ambulance approaches with siren and flashing lights from behind at a red light. You are first in line. Which sequence is correct AND legal?",
    choices:["Run the red to clear the way","Stay put — running the light is illegal; pull as far right as possible ONLY once you may legally proceed","Reverse onto the sidewalk","Follow the ambulance through"],
    a:1,
    why:"Never break a signal for an emergency vehicle — you become the hazard. Stay stopped at the red, keep the intersection clear, and when your light allows, pull right and stop so the rig can pass. Intersections belong to them once they enter.",
    sourceId:"us-dmv-handbooks-composite" },
];

/* Quick self-check on load (dev aid): every question has a valid answer index. */
if (typeof window !== "undefined") {
  QUESTIONS.forEach(q => {
    if (!q.choices || q.a < 0 || q.a >= q.choices.length) console.error("Bad question:", q.id);
    if (!CATEGORIES[q.cat]) console.error("Bad category:", q.id, q.cat);
    if (q.signId && typeof SIGNS === "undefined" || q.signId && !SIGNS[q.signId]) console.error("Bad sign:", q.id, q.signId);
  });
}
