/* Road Ready — state-specific content packs.
 *
 * Content model:
 *   Universal concepts  — js/questions.js (no jurisdiction tag): signs,
 *                         hazard recognition, positioning, following distance,
 *                         basic right-of-way. Rules common across states.
 *   Jurisdiction layer  — below. Each pack carries its own question set
 *                         (jurisdiction:["XX"], concept, sourceId/sourceSection)
 *                         plus key-fact overrides shown in the study guide.
 * The selected pack (settings.statePack) filters the active bank and swaps the
 * facts card. "generic" = universal questions only.
 */
"use strict";

/* Primary-source registry. Every jurisdictional question must resolve to one
   of these issuing-agency resources; content QA enforces the relationship. */
const SOURCE_REGISTRY = {
  "ca-dmv-driver-handbook": {
    jurisdiction: "CA", agency: "California DMV", title: "California Driver's Handbook",
    url: "https://www.dmv.ca.gov/portal/handbook/california-driver-handbook/", verified: "2026-08-23",
  },
  "tx-dps-driver-handbook": {
    jurisdiction: "TX", agency: "Texas DPS", title: "Texas Driver Handbook",
    url: "https://www.dps.texas.gov/InternetForms/home/Details/304", verified: "2026-08-23",
  },
  "ny-dmv-driver-manual": {
    jurisdiction: "NY", agency: "New York DMV", title: "New York State Driver's Manual",
    url: "https://dmv.ny.gov/book/export/html/1551", verified: "2026-08-23",
  },
  "fl-flhsmv-handbook": {
    jurisdiction: "FL", agency: "FLHSMV", title: "Official Florida Driver License Handbook",
    url: "https://www.flhsmv.gov/pdf/handbooks/englishdriverhandbook.pdf", verified: "2026-08-23",
  },
  "wa-dol-driver-guide": {
    jurisdiction: "WA", agency: "Washington DOL", title: "Washington State Driver Guide",
    url: "https://dol.wa.gov/driver-licenses-and-permits/driver-training-and-testing/driver-guides/washington-state-driver-guide-text-only", verified: "2026-08-23",
  },
  "pa-penndot-driver-manual": {
    jurisdiction: "PA", agency: "PennDOT", title: "Pennsylvania Driver's Manual",
    url: "https://www.pa.gov/agencies/dmv/driver-services/pennsylvania-drivers-manual", verified: "2026-08-23",
  },
  "uk-highway-code": {
    jurisdiction: "UK", agency: "Department for Transport", title: "The Highway Code",
    url: "https://www.gov.uk/guidance/the-highway-code", verified: "2026-09-22",
  },
  "uk-know-your-traffic-signs": {
    jurisdiction: "UK", agency: "Department for Transport", title: "Know Your Traffic Signs",
    url: "https://www.gov.uk/government/publications/know-your-traffic-signs", verified: "2026-09-22",
  },
  "uk-theory-test-format": {
    jurisdiction: "UK", agency: "DVSA", title: "Theory test: cars — multiple-choice format",
    url: "https://www.gov.uk/theory-test/multiple-choice-questions", verified: "2026-09-22",
    note: "50 questions and 57 minutes are stated on this page; the 43/50 pass mark was independently re-verified on GOV.UK's pass-mark page on 2026-09-22.",
  },
  "us-dmv-handbooks-composite": {
    jurisdiction: "*", agency: "Multiple state DMVs (composite)",
    title: "U.S. state driver handbooks — commonly taught rules",
    edition: "2025–2026 editions", verified: "2026-08-23",
    note: "Cites the universal bank: rules taught consistently across state handbooks. State exceptions live in jurisdiction packs.",
  },
};

/* Explicit, reviewed per-category citations for the universal bank. This table
   IS the provenance for universal questions — configuration, never a silent
   tooling fallback. A question whose cat has no entry here FAILS content QA. */
const UNIVERSAL_DEFAULTS = {
  signs:      { sourceId: "us-dmv-handbooks-composite", section: "Traffic Signs and Signals" },
  markings:   { sourceId: "us-dmv-handbooks-composite", section: "Pavement Markings" },
  row:        { sourceId: "us-dmv-handbooks-composite", section: "Right of Way" },
  speed:      { sourceId: "us-dmv-handbooks-composite", section: "Speed Limits and Safe Speed" },
  parking:    { sourceId: "us-dmv-handbooks-composite", section: "Parking and Stopping" },
  alcohol:    { sourceId: "us-dmv-handbooks-composite", section: "Alcohol and Drugs" },
  safety:     { sourceId: "us-dmv-handbooks-composite", section: "Safe Driving and Emergencies" },
  vulnerable: { sourceId: "us-dmv-handbooks-composite", section: "Sharing the Road" },
  vehicle:    { sourceId: "us-dmv-handbooks-composite", section: "Vehicle Equipment and Maintenance" },
  laws:       { sourceId: "us-dmv-handbooks-composite", section: "Licensing, Documents and Penalties" },
};

/* How fresh a source verification must be (days). Older = CI failure. */
const VERIFICATION_MAX_AGE_DAYS = 365;

/* Which fact-table column guards which concept — used by the fact-consistency
   checker to cross-examine state-specific answers against pack facts. */
const CONCEPT_FACT_KEYS = {
  "bac-limits":         ["bacAdult"],
  "zero-tolerance":     ["bacUnder21"],
  "following-distance": ["followDistance"],
  "school-bus":         ["schoolBus"],
  "right-on-red":       ["rightOnRed"],
  "speed-limits":       ["speedResidential", "speedUrban"],
  "phone-use":          ["handsFree", "handheldPhone", "distractedDriving", "textingBan"],
  "distracted-driving": ["distractedDriving", "handsFree", "handheldPhone"],
  "move-over":          ["moveOver"],
  "bike-passing-distance": ["bikePassing"],
  "work-zones":         ["workZone"],
};

const STATE_PACKS = {
  generic: {
    id: "generic",
    includeUniversal: true,
    name: "General U.S. rules",
    note: "Follows rules common across state DMV handbooks. Confirm specifics with your official handbook.",
    facts: {
      bacAdult: "0.08%",
      bacUnder21: "zero tolerance (any measurable amount)",
      followDistance: "3-second rule",
      rightOnRed: "Allowed after a complete stop unless posted otherwise",
      schoolBus: "Stop in both directions when red lights flash (divided highways may exempt oncoming traffic)",
    },
    questions: [],
  },
  CA: {
    id: "CA",
    name: "California (DMV)",
    sourceId: "ca-dmv-driver-handbook",
    facts: {
      bacAdult: "0.08% (0.04% for commercial drivers)",
      bacUnder21: "0.01% or more — zero tolerance",
      followDistance: "3-second rule",
      rightOnRed: "Allowed after a complete stop unless a sign prohibits it",
      schoolBus: "Stop in both directions on undivided roads when red lights flash",
      speedResidential: "25 mph",
        bikePassing: "At least 3 feet when passing a bicycle",
      handsFree: "No handheld phone use at all for drivers 18+; under-18 drivers may not use a phone even hands-free",
    },
    questions: [
      { id: "ca-001", cat: "alcohol", jurisdiction: ["CA"], concept: "zero-tolerance",
        q: "In California, a driver under 21 may be cited for DUI with a BAC of:",
        choices: ["0.08% or more", "0.05% or more", "0.01% or more — any measurable amount", "There is no limit for minors"],
        a: 2,
        why: "California's zero-tolerance law (Vehicle Code §23136) suspends the license of any driver under 21 measuring 0.01% BAC or more — essentially one drink. Drivers 21+ are held to the 0.08% limit.",
        sourceId: "ca-dmv-driver-handbook", sourceSection: "Alcohol and Drugs" },
      { id: "ca-002", cat: "alcohol", jurisdiction: ["CA"], concept: "bac-limits",
        q: "A California commercial driver operates under a BAC limit of:",
        choices: ["0.08%", "0.04%", "0.10%", "The same limit as other drivers"],
        a: 1,
        why: "Commercial drivers in California are limited to 0.04% BAC — half the standard 0.08% limit — because of the size and risk of the vehicles they operate.",
        sourceId: "ca-dmv-driver-handbook", sourceSection: "Commercial Licenses" },
      { id: "ca-003", cat: "speed", jurisdiction: ["CA"], concept: "speed-limits",
        q: "Unless a posted sign says otherwise, the speed limit in a California residential district is:",
        choices: ["30 mph", "25 mph", "20 mph", "35 mph"],
        a: 1,
        why: "California's default residential/business-district speed limit is 25 mph when no sign posts a different number. Blanket limits like this apply where you see no signage.",
        sourceId: "ca-dmv-driver-handbook", sourceSection: "Traffic Controls" },
      { id: "ca-004", cat: "laws", jurisdiction: ["CA"], concept: "phone-use",
        q: "A California driver under 18 who holds a provisional license may use a phone while driving:",
        choices: ["Only with a hands-free device", "Only at a red light", "Never — not even hands-free", "Only for navigation"],
        a: 2,
        why: "Under-18 provisional licensees in California may not use a phone at all while driving, even hands-free — the distraction, not just the handset, is the hazard. Drivers 18+ may use hands-free only.",
        sourceId: "ca-dmv-driver-handbook", sourceSection: "Distractions" },
      { id: "ca-005", cat: "vulnerable", jurisdiction: ["CA"], concept: "school-bus",
        q: "On an undivided California road, a school bus flashes red lights as children board. You must:",
        choices: ["Pass slowly on the left", "Stop in both directions until the lights stop", "Stop only if you are behind the bus", "Slow to 25 mph and continue"],
        a: 1,
        why: "On undivided roads, traffic in BOTH directions must stop for a school bus flashing red lights and remain stopped until the lights stop flashing. Only divided-highway oncoming traffic may continue.",
        sourceId: "ca-dmv-driver-handbook", sourceSection: "School Buses" },
      { id: "ca-006", cat: "row", jurisdiction: ["CA"], concept: "right-on-red",
        q: "At a California red light with no prohibiting sign, you may turn right after:",
        choices: ["Slowing to 10 mph", "Coming to a complete stop and yielding", "Waiting for one full cycle", "Flashing your headlights"],
        a: 1,
        why: "Right on red is legal in California unless a sign prohibits it — but only after a COMPLETE stop and yielding to pedestrians and cross traffic. A rolling 'California stop' is still a violation.",
        sourceId: "ca-dmv-driver-handbook", sourceSection: "Right of Way" },
        { id: "ca-007", cat: "vulnerable", jurisdiction: ["CA"], concept: "bike-passing-distance",
          q: "Under California law, when you pass a bicycle you must leave at least:",
          choices: ["1 foot of clearance", "2 feet of clearance", "3 feet of clearance", "A car's length"],
          a: 2,
          why: "California requires AT LEAST THREE FEET between your vehicle and a bicycle when passing — and to slow further if you cannot get that far over.",
          sourceId: "ca-dmv-driver-handbook", sourceSection: "Sharing the Road" },
    ],
  },
  TX: {
    id: "TX",
    name: "Texas (DPS)",
    sourceId: "tx-dps-driver-handbook",
    facts: {
      bacAdult: "0.08%",
      bacUnder21: "any detectable amount",
      followDistance: "2-second minimum, more at speed or in rain",
      rightOnRed: "Allowed after a complete stop unless posted otherwise",
      schoolBus: "Stop in both directions on any road unless a physical barrier divides them",
        speedUrban: "30 mph default in cities unless posted",
        textingBan: "Texting while driving is illegal for ALL drivers statewide",
    },
    questions: [
      { id: "tx-001", cat: "alcohol", jurisdiction: ["TX"], concept: "zero-tolerance",
        q: "Under Texas zero-tolerance law, a driver under 21 commits an offense with:",
        choices: ["A BAC of 0.08%", "Any detectable amount of alcohol", "A BAC above 0.04%", "Open containers in the trunk"],
        a: 1,
        why: "Texas forbids ANY detectable amount of alcohol for drivers under 21 — there is no minimum threshold like the adult 0.08% limit.",
        sourceId: "tx-dps-driver-handbook", sourceSection: "Alcohol and Drug Impact" },
      { id: "tx-002", cat: "speed", jurisdiction: ["TX"], concept: "speed-limits",
        q: "In a Texas city street with no posted speed limit, the urban district limit is generally:",
        choices: ["25 mph", "30 mph", "40 mph", "55 mph"],
        a: 1,
        why: "Texas urban districts default to 30 mph unless signage posts otherwise. Rural highways carry higher defaults — always look for signs first.",
        sourceId: "tx-dps-driver-handbook", sourceSection: "Signs, Signals and Markings" },
      { id: "tx-003", cat: "vulnerable", jurisdiction: ["TX"], concept: "school-bus",
        q: "A Texas school bus stops with red lights flashing on a road separated by a raised concrete median. Oncoming traffic:",
        choices: ["Must stop in both directions", "May continue if separated by a physical barrier", "Must slow to 15 mph", "Must stop until children are visible"],
        a: 1,
        why: "Texas requires stopping in both directions UNLESS a physical barrier (raised median or barrier) divides the road — paint alone does not exempt oncoming traffic.",
        sourceId: "tx-dps-driver-handbook", sourceSection: "Right of Way" },
      { id: "tx-004", cat: "safety", jurisdiction: ["TX"], concept: "following-distance",
        q: "Texas guidance recommends a following distance of at least:",
        choices: ["One second per 20 mph", "Two seconds, extended in rain or at speed", "Half a car length", "Ten feet per 10 mph"],
        a: 1,
        why: "Texas teaches a two-second minimum gap, stretched further at highway speeds or in poor weather — count 'one-thousand-one, one-thousand-two' between the car ahead passing a fixed point and you reaching it.",
        sourceId: "tx-dps-driver-handbook", sourceSection: "Defensive Driving" },
      { id: "tx-005", cat: "row", jurisdiction: ["TX"], concept: "right-on-red",
        q: "In Texas, a right turn on red is:",
        choices: ["Always illegal in cities", "Allowed after a complete stop unless a sign prohibits it", "Allowed without stopping", "Only allowed on green arrows"],
        a: 1,
        why: "Texas permits right on red after a complete stop and yielding, unless a posted sign forbids it at that intersection.",
        sourceId: "tx-dps-driver-handbook", sourceSection: "Traffic Laws" },
      { id: "tx-006", cat: "laws", jurisdiction: ["TX"], concept: "phone-use",
        q: "Texas statewide law restricts texting while driving by:",
        choices: ["Banning it for all drivers", "Allowing it at red lights", "Banning it only for minors", "Leaving it entirely to cities"],
        a: 0,
        why: "Texas bans reading, writing, or sending electronic messages while driving for ALL drivers statewide — many cities add stricter local ordinances.",
        sourceId: "tx-dps-driver-handbook", sourceSection: "Distractions" },
    ],
  },
  NY: {
    id: "NY",
    name: "New York (DMV)",
    sourceId: "ny-dmv-driver-manual",
    facts: {
      bacAdult: "0.08% (0.18% is aggravated DWI)",
      bacUnder21: "0.02% — zero tolerance",
      followDistance: "4-second rule recommended",
      rightOnRed: "Allowed after stop unless a sign prohibits it; NEVER in New York City, where it is prohibited citywide",
      schoolBus: "Stop in both directions, even on divided highways",
      handheldPhone: "Portable-electronics ban — fines plus points on your license",
    },
    questions: [
      { id: "ny-001", cat: "row", jurisdiction: ["NY"], concept: "right-on-red",
        q: "You stop at a red light in New York City with no signs about turning. You may turn right:",
        choices: ["After a complete stop", "Never — right on red is prohibited citywide in NYC", "Only between 9am and 5pm", "Only onto one-way streets"],
        a: 1,
        why: "New York City prohibits right turn on red EVERYWHERE within city limits unless a sign expressly allows it. In the rest of New York State, right on red follows the usual after-a-complete-stop rule.",
        sourceId: "ny-dmv-driver-manual", sourceSection: "Traffic Control" },
      { id: "ny-002", cat: "alcohol", jurisdiction: ["NY"], concept: "zero-tolerance",
        q: "New York's zero-tolerance law for drivers under 21 starts at a BAC of:",
        choices: ["0.08%", "0.05%", "0.02%", "0.10%"],
        a: 2,
        why: "New York drivers under 21 face license suspension at just 0.02% BAC — well under the 0.08% adult DWI threshold.",
        sourceId: "ny-dmv-driver-manual", sourceSection: "Alcohol and Drugs" },
      { id: "ny-003", cat: "alcohol", jurisdiction: ["NY"], concept: "bac-limits",
        q: "A New York driver arrested at a 0.19% BAC faces:",
        choices: ["Standard DWI charges only", "Aggravated DWI — harsher penalties", "No charge below 0.20%", "Only a warning for a first offense"],
        a: 1,
        why: "New York elevates DWI at or above 0.18% BAC to AGGRAVATED DWI, carrying steeper fines and longer license revocation than a standard 0.08% DWI.",
        sourceId: "ny-dmv-driver-manual", sourceSection: "Alcohol and Drugs" },
      { id: "ny-004", cat: "laws", jurisdiction: ["NY"], concept: "phone-use",
        q: "Using a portable electronic device while driving in New York results in:",
        choices: ["Nothing, if driving carefully", "A fine only", "A fine AND points on your license", "Points only for repeat offenses"],
        a: 2,
        why: "New York's handheld-device ban adds POINTS to your license on top of fines — five points for a first conviction — because distraction crashes are a leading killer.",
        sourceId: "ny-dmv-driver-manual", sourceSection: "Distractions" },
      { id: "ny-005", cat: "vulnerable", jurisdiction: ["NY"], concept: "school-bus",
        q: "New York school bus rules require oncoming traffic on a DIVIDED highway to:",
        choices: ["Continue normally", "Stop along with same-direction traffic", "Slow to 15 mph", "Stop only for flashing red lights on their side"],
        a: 1,
        why: "New York is stricter than most states: even on divided highways, traffic in BOTH directions must stop for a school bus displaying flashing red lights.",
        sourceId: "ny-dmv-driver-manual", sourceSection: "School Buses" },
      { id: "ny-006", cat: "safety", jurisdiction: ["NY"], concept: "following-distance",
        q: "The New York DMV recommends keeping a following distance of:",
        choices: ["One second", "Two seconds", "About four seconds", "Half a block"],
        a: 2,
        why: "New York teaches roughly FOUR seconds of following space — longer than the classic two/three-second rules — to leave room for reaction plus braking in dense traffic.",
        sourceId: "ny-dmv-driver-manual", sourceSection: "Defensive Driving" },
    ],
  },
  FL: {
    id: "FL",
    name: "Florida (FLHSMV)",
    sourceId: "fl-flhsmv-handbook",
    facts: {
      bacAdult: "0.08%",
      bacUnder21: "0.02% or more",
      followDistance: "3-second rule, 4+ in rain",
      rightOnRed: "Allowed after a complete stop unless posted otherwise",
      schoolBus: "Stop in both directions unless a median divides the road",
      moveOver: "Move over one lane (or slow 20 mph below the limit) for stopped emergency/service vehicles",
    },
    questions: [
      { id: "fl-001", cat: "laws", jurisdiction: ["FL"], concept: "move-over",
        q: "Passing a tow truck working beside a Florida interstate lane, you should:",
        choices: ["Maintain speed and position", "Move over a lane, or slow to 20 mph below the limit if you cannot", "Sound your horn to warn the operator", "Stop completely in your lane"],
        a: 1,
        why: "Florida's Move Over Act requires changing lanes away from stopped emergency/service/tow vehicles — or, when you can't change lanes, slowing to 20 mph BELOW the posted limit.",
        sourceId: "fl-flhsmv-handbook", sourceSection: "Sharing the Road" },
      { id: "fl-002", cat: "alcohol", jurisdiction: ["FL"], concept: "zero-tolerance",
        q: "For drivers under 21 in Florida, the administrative penalty begins at a BAC of:",
        choices: ["0.08%", "0.04%", "0.02%", "0.10%"],
        a: 2,
        why: "Florida suspends the license of under-21 drivers measuring 0.02% BAC or more — roughly a single serving of alcohol.",
        sourceId: "fl-flhsmv-handbook", sourceSection: "Driving Under the Influence" },
      { id: "fl-003", cat: "vulnerable", jurisdiction: ["FL"], concept: "school-bus",
        q: "On a Florida road with a painted center turn lane but NO physical median, oncoming traffic meeting a stopped school bus with flashing reds must:",
        choices: ["Continue at reduced speed", "Stop in both directions", "Stop only on the bus's side", "Change lanes and pass"],
        a: 1,
        why: "Florida exempts oncoming traffic ONLY when a PHYSICAL median divides the roadway. Pavement markings like a turn lane do NOT exempt you — both directions stop.",
        sourceId: "fl-flhsmv-handbook", sourceSection: "School Bus Safety" },
      { id: "fl-004", cat: "safety", jurisdiction: ["FL"], concept: "following-distance",
        q: "Driving in heavy Florida rain, your following distance should be:",
        choices: ["One second", "Three seconds or more — extend to four+", "Shorter so drivers can't cut in", "Unchanged from dry conditions"],
        a: 1,
        why: "Florida teaches three seconds dry, extending beyond four in rain — wet pavement can double braking distance, and sudden downpours are routine.",
        sourceId: "fl-flhsmv-handbook", sourceSection: "Defensive Driving" },
      { id: "fl-005", cat: "row", jurisdiction: ["FL"], concept: "right-on-red",
        q: "In Florida, right turn on red is permitted:",
        choices: ["Everywhere, at any speed", "After a complete stop unless posted otherwise", "Only outside cities", "Only when a police officer signals"],
        a: 1,
        why: "Florida allows right on red after a FULL stop and yielding to pedestrians/cross traffic, unless a sign prohibits the turn at that intersection.",
        sourceId: "fl-flhsmv-handbook", sourceSection: "Signals and Signs" },
      { id: "fl-006", cat: "alcohol", jurisdiction: ["FL"], concept: "bac-limits",
        q: "The standard adult DUI limit in Florida is a BAC of:",
        choices: ["0.05%", "0.08%", "0.10%", "0.15%"],
        a: 1,
        why: "Florida presumes impairment at 0.08% BAC for drivers 21 and older, matching the nationwide standard — impairment can begin well below the legal line.",
        sourceId: "fl-flhsmv-handbook", sourceSection: "Driving Under the Influence" },
    ],
  },
  WA: {
    id: "WA",
    name: "Washington (DOL)",
    sourceId: "wa-dol-driver-guide",
    facts: {
      bacAdult: "0.08%",
      bacUnder21: "0.02% or more",
      followDistance: "4-second rule in adverse conditions",
      rightOnRed: "Allowed after a complete stop unless posted otherwise",
      schoolBus: "Stop in both directions unless four or more lanes are divided by a median",
      distractedDriving: "E-DUI law — even holding a phone at a light is an offense",
    },
    questions: [
      { id: "wa-001", cat: "laws", jurisdiction: ["WA"], concept: "distracted-driving",
        q: "Under Washington's E-DUI law, holding your phone at a red light is:",
        choices: ["Legal — you are not moving", "Legal for navigation only", "An offense — the law covers stops at lights too", "Only a secondary violation"],
        a: 2,
        why: "Washington's Driving Under the Influence of Electronics (E-DUI) act applies even when temporarily stopped at a light or sign — hold the phone, commit the offense.",
        sourceId: "wa-dol-driver-guide", sourceSection: "Rules of the Road" },
      { id: "wa-002", cat: "alcohol", jurisdiction: ["WA"], concept: "zero-tolerance",
        q: "A Washington driver under 21 exceeds zero tolerance at a BAC of:",
        choices: ["0.08%", "0.05%", "0.02%", "Any amount whatsoever"],
        a: 2,
        why: "Washington sets its under-21 threshold at 0.02% BAC for the administrative offense, alongside the adult 0.08% DUI limit.",
        sourceId: "wa-dol-driver-guide", sourceSection: "Alcohol and Drugs" },
      { id: "wa-003", cat: "vulnerable", jurisdiction: ["WA"], concept: "school-bus",
        q: "On a Washington road with four lanes divided by a median, oncoming traffic facing a stopped school bus with flashing reds:",
        choices: ["Must stop in all cases", "May proceed with caution — four-lane divided roads are exempt", "Must stop for 30 seconds", "Must honk before proceeding"],
        a: 1,
        why: "Washington exempts oncoming traffic only on roads of FOUR OR MORE lanes separated by a median; on smaller undivided roads, both directions stop.",
        sourceId: "wa-dol-driver-guide", sourceSection: "School Bus Rules" },
      { id: "wa-004", cat: "safety", jurisdiction: ["WA"], concept: "following-distance",
        q: "In Washington's frequent rain, the DOL suggests a following distance of:",
        choices: ["Two seconds flat", "About four seconds", "One car length per 5 mph", "As close as visibility allows"],
        a: 1,
        why: "Washington extends the following interval to around four seconds in adverse weather — wet roads lengthen stopping distance dramatically.",
        sourceId: "wa-dol-driver-guide", sourceSection: "Defensive Driving" },
      { id: "wa-005", cat: "row", jurisdiction: ["WA"], concept: "right-on-red",
        q: "Unless a sign prohibits it, a Washington driver may turn right on red after:",
        choices: ["Yielding once", "A complete stop and yielding to pedestrians and cross traffic", "Signaling for ten seconds", "Coming to a rolling stop"],
        a: 1,
        why: "Washington permits right on red following a full stop and yield — the same baseline rule used across most U.S. jurisdictions.",
        sourceId: "wa-dol-driver-guide", sourceSection: "Intersections" },
      { id: "wa-006", cat: "alcohol", jurisdiction: ["WA"], concept: "bac-limits",
        q: "The per-se DUI blood-alcohol level for adults in Washington is:",
        choices: ["0.08%", "0.10%", "0.05%", "0.02%"],
        a: 0,
        why: "Washington's adult legal limit is 0.08% BAC; at or above that figure you are legally presumed under the influence.",
        sourceId: "wa-dol-driver-guide", sourceSection: "Alcohol and Drugs" },
    ],
  },
  PA: {
    id: "PA",
    name: "Pennsylvania (PennDOT)",
    sourceId: "pa-penndot-driver-manual",
    facts: {
      bacAdult: "0.08% (higher DUI tiers at 0.10% and 0.16%)",
      bacUnder21: "0.02% or more",
      followDistance: "4-second rule in poor conditions",
      rightOnRed: "Allowed after a complete stop unless posted otherwise (Philadelphia restrictions apply)",
      schoolBus: "Stop at least 10 feet away; both directions on non-divided roads",
      workZone: "Work-zone violations carry doubled fines and mandatory penalties",
        bikePassing: "At least 4 feet when overtaking a bicycle",
    },
    questions: [
      { id: "pa-001", cat: "laws", jurisdiction: ["PA"], concept: "work-zones",
        q: "Committing a speeding violation inside an active Pennsylvania work zone brings:",
        choices: ["A written warning", "Doubled fines and mandatory penalties", "Nothing if workers aren't visible", "A small flat fee"],
        a: 1,
        why: "Pennsylvania doubles fines for work-zone violations and attaches mandatory penalties — safety corridors protect workers with little physical shielding.",
        sourceId: "pa-penndot-driver-manual", sourceSection: "Work Zones" },
      { id: "pa-002", cat: "vulnerable", jurisdiction: ["PA"], concept: "school-bus",
        q: "Meeting a Pennsylvania school bus with flashing red lights on a non-divided road, you must stop:",
        choices: ["Within 50 feet", "At least 10 feet away, in both directions", "Only on the bus's side", "Wherever convenient"],
        a: 1,
        why: "Pennsylvania requires stopping AT LEAST 10 FEET from the bus, in both directions on non-divided roads, until the reds stop flashing.",
        sourceId: "pa-penndot-driver-manual", sourceSection: "School Bus Stopping" },
      { id: "pa-003", cat: "alcohol", jurisdiction: ["PA"], concept: "bac-limits",
        q: "Pennsylvania escalates DUI penalties into a 'high-rate' tier beginning at a BAC of:",
        choices: ["0.08%", "0.10%", "0.16%", "0.20%"],
        a: 1,
        why: "Pennsylvania tiers DUI: general impairment at 0.08%, HIGH rate at 0.10%, and HIGHEST rate at 0.16% — penalties grow sharply at each tier.",
        sourceId: "pa-penndot-driver-manual", sourceSection: "Driving Under the Influence" },
      { id: "pa-004", cat: "alcohol", jurisdiction: ["PA"], concept: "zero-tolerance",
        q: "Pennsylvania's zero-tolerance BAC threshold for drivers under 21 is:",
        choices: ["0.02% or more", "0.05% or more", "0.08% or more", "Any trace at all"],
        a: 0,
        why: "Pennsylvania suspends under-21 drivers at 0.02% BAC OR MORE under its zero-tolerance provision — the answer, restated: 0.02% or more.",
        sourceId: "pa-penndot-driver-manual", sourceSection: "Young Drivers" },
      { id: "pa-005", cat: "safety", jurisdiction: ["PA"], concept: "following-distance",
        q: "Pennsylvania recommends increasing your normal following distance to about four seconds when:",
        choices: ["Following motorcycles only", "Roads are wet, icy, or visibility is poor", "Driving in cities", "Towing is illegal"],
        a: 1,
        why: "PennDOT's four-second guideline applies in poor conditions — rain, snow, ice, fog — when braking and reaction both degrade.",
        sourceId: "pa-penndot-driver-manual", sourceSection: "Defensive Driving" },
      { id: "pa-006", cat: "row", jurisdiction: ["PA"], concept: "right-on-red",
        q: "Which Pennsylvania location restricts right turns on red more aggressively than the rest of the state?",
        choices: ["Pittsburgh", "Philadelphia", "Harrisburg", "Scranton"],
        a: 1,
        why: "While Pennsylvania generally allows right on red after a complete stop, Philadelphia applies citywide restrictions where turns on red are barred unless signed otherwise.",
        sourceId: "pa-penndot-driver-manual", sourceSection: "Traffic Signals" },
        { id: "pa-007", cat: "vulnerable", jurisdiction: ["PA"], concept: "bike-passing-distance",
          q: "In Pennsylvania, the minimum distance to allow when overtaking a bicycle is:",
          choices: ["2 feet", "3 feet", "4 feet", "No minimum — just don't hit them"],
          a: 2,
          why: "Pennsylvania requires AT LEAST FOUR FEET of clearance when overtaking a bicycle — one foot more than most states. If you cannot pass with four feet, wait until you can.",
          sourceId: "pa-penndot-driver-manual", sourceSection: "Sharing the Road" },
    ],
  },
  UK: {
    id: "UK",
    includeUniversal: false,
    name: "Great Britain (DVSA car)",
    sourceId: "uk-highway-code",
    facts: {
      bacAdult: "35 microgrammes per 100ml breath in England and Wales; 22 in Scotland",
      bacUnder21: "No separate under-21 limit: the same regional adult limit applies (35 England/Wales; 22 Scotland)",
      rightOnRed: "Not applicable — drive on the left; never pass a red light",
      followDistance: "2-second rule in dry conditions (at least 4 seconds in the wet)",
      speedResidential: "30 mph in England and Scotland; 20 mph in Wales on lit built-up roads unless signs show otherwise",
      speedUrban: "60 mph single carriageway / 70 mph dual carriageway and motorway (cars)",
      bikePassing: "At least 1.5 metres when overtaking cyclists at up to 30 mph (more at higher speeds)",
      handsFree: "Hand-held phone ban — 6 points and £200 fine",
      theoryFormat: "50 questions in 57 minutes, 43 to pass",
      hazardFormat: "14 clips, 15 hazards, 44 out of 75 to pass",
    },
    questions: [
      { id: "uk-001", cat: "signs", jurisdiction: ["UK"], concept: "national-speed-limit-sign",
        q: "You see a white circular sign with a single black diagonal bar. What does it mean?",
        choices: ["End of motorway", "National speed limit applies", "No overtaking", "Minimum speed limit"],
        a: 1,
        why: "The white circle with a black diagonal is the national-speed-limit sign: the default maximum for that road class applies. On lit built-up roads that still means 30 mph unless signs say otherwise.",
        sourceId: "uk-know-your-traffic-signs", sourceSection: "Speed limit signs" },
      { id: "uk-002", cat: "signs", jurisdiction: ["UK"], concept: "warning-vs-order-signs",
        q: "In the UK sign system, what is the difference between a red triangle and a red circle?",
        choices: ["Triangles give orders, circles warn", "Triangles warn of hazards ahead; circles give orders you must obey", "Circles are advisory only", "There is no difference"],
        a: 1,
        why: "Shape carries the meaning: red triangles warn of hazards ahead, while red circles give prohibitive orders. Learning the shape system lets you react before reading the symbol.",
        sourceId: "uk-know-your-traffic-signs", sourceSection: "Sign shapes" },
      { id: "uk-003", cat: "speed", jurisdiction: ["UK"], concept: "speed-limits",
        q: "A car on a UK single carriageway with no other limit signed may travel at up to:",
        choices: ["50 mph", "60 mph", "70 mph", "40 mph"],
        a: 1,
        why: "The national limit for cars on a single carriageway is 60 mph. Dual carriageways and motorways allow 70 mph for cars; built-up lit roads default to 30 mph.",
        sourceId: "uk-highway-code", sourceSection: "Speed limits" },
      { id: "uk-004", cat: "speed", jurisdiction: ["UK"], concept: "speed-limits",
        q: "In England or Scotland, a lit built-up road has no signs showing a different limit. What limit generally applies?",
        choices: ["20 mph", "30 mph", "40 mph", "60 mph"],
        a: 1,
        why: "In England and Scotland, 30 mph generally applies on roads with street lights unless signs show otherwise. In Wales, the equivalent default is generally 20 mph.",
        sourceId: "uk-highway-code", sourceSection: "Speed limits" },
      { id: "uk-005", cat: "row", jurisdiction: ["UK"], concept: "roundabout-priority",
        q: "At a UK roundabout with no traffic lights, you must give way to:",
        choices: ["Traffic from your left", "Traffic from your right", "Cyclists behind you only", "Nobody — first to enter wins"],
        a: 1,
        why: "Give way to traffic coming from your right, circulating on the roundabout. The Highway Code rule is explicit: priority goes to the right on UK roundabouts.",
        sourceId: "uk-highway-code", sourceSection: "Roundabouts" },
      { id: "uk-006", cat: "vulnerable", jurisdiction: ["UK"], concept: "zebra-crossing",
        q: "A pedestrian steps onto a zebra crossing ahead of you. You must:",
        choices: ["Wave them back and drive through", "Stop and let them cross", "Sound the horn and continue", "Overtake on the zig-zags if clear"],
        a: 1,
        why: "Zebra crossings give pedestrians priority once they step on: stop at the give-way line and wait. Overtaking and parking on the zig-zag lines is banned because it hides people crossing.",
        sourceId: "uk-highway-code", sourceSection: "Pedestrian crossings" },
      { id: "uk-007", cat: "vulnerable", jurisdiction: ["UK"], concept: "bike-passing-distance",
        q: "Overtaking a cyclist at up to 30 mph, the Highway Code says leave at least:",
        choices: ["0.5 metres", "1.5 metres", "3 metres", "Whatever feels close enough"],
        a: 1,
        why: "Leave AT LEAST 1.5 METRES when passing cyclists at up to 30 mph, and more space at higher speeds. Close passes are a leading cause of cyclist injuries.",
        sourceId: "uk-highway-code", sourceSection: "Overtaking cyclists" },
      { id: "uk-008", cat: "safety", jurisdiction: ["UK"], concept: "following-distance",
        q: "In dry conditions on a UK road, the recommended gap to the vehicle ahead is:",
        choices: ["A 1-second gap", "A 2-second gap", "A 5-second gap", "One car length at any speed"],
        a: 1,
        why: "Use the 2-SECOND rule in the dry: pick a fixed point and count two seconds after the vehicle ahead passes it. Double the gap to at least 4 seconds when wet.",
        sourceId: "uk-highway-code", sourceSection: "Stopping distances" },
      { id: "uk-009", cat: "laws", jurisdiction: ["UK"], concept: "phone-use",
        q: "Caught using a hand-held phone while driving in the UK, you face:",
        choices: ["A warning letter only", "6 penalty points and a £200 fine", "An instant driving ban in all cases", "No penalty if stationary at lights"],
        a: 1,
        why: "Hand-held use is banned even when stopped at lights or in queues: the penalty is 6 POINTS and a £200 FINE. New drivers can lose their licence on 6 points within two years of passing.",
        sourceId: "uk-highway-code", sourceSection: "Mobile phones" },
      { id: "uk-010", cat: "alcohol", jurisdiction: ["UK"], concept: "bac-limits",
        q: "The drink-drive breath limit in England and Wales is:",
        choices: ["15 microgrammes per 100ml", "25 microgrammes per 100ml", "35 microgrammes per 100ml", "80 microgrammes per 100ml"],
        a: 2,
        why: "England and Wales set the breath limit at 35 MICROGRAMMES of alcohol per 100ml of breath. Scotland is stricter at 22. Any amount impairs driving — the limit is a legal ceiling, not a safe target.",
        sourceId: "uk-highway-code", sourceSection: "Drink and drugs" },
      { id: "uk-011", cat: "markings", jurisdiction: ["UK"], concept: "motorway-lanes",
        q: "On a UK motorway you should normally drive in:",
        choices: ["The right-hand lane", "The left-hand lane, overtaking on the right", "The hard shoulder", "Whichever lane is emptiest, weaving as needed"],
        a: 1,
        why: "Keep left unless overtaking: the left-hand lane is the driving lane and you pass on the right. Middle-lane hogging can draw a careless-driving penalty.",
        sourceId: "uk-highway-code", sourceSection: "Motorways" },
      { id: "uk-012", cat: "alcohol", jurisdiction: ["UK"], concept: "bac-limits",
        q: "What is the legal breath-alcohol limit for drivers in Scotland?",
        choices: ["35 microgrammes per 100ml", "22 microgrammes per 100ml", "50 microgrammes per 100ml", "80 microgrammes per 100ml"],
        a: 1,
        why: "Scotland has a lower limit than England and Wales: 22 MICROGRAMMES of alcohol per 100ml of breath, compared with 35 in England and Wales.",
        sourceId: "uk-highway-code", sourceSection: "Alcohol and drugs — Rule 95" },
      {"id":"uk-013","cat":"signs","jurisdiction":["UK"],"concept":"traffic-lights-red-amber","q":"At traffic lights, red and amber are showing together. What should you do?","choices":["Stay stopped and wait for green","Move off if no traffic is coming","Prepare to turn only","Proceed slowly through the junction"],"a":0,"why":"Red and amber still mean stop. Do not cross the stop line or start moving until green shows.","sourceId":"uk-highway-code","sourceSection":"Light signals controlling traffic"},
      {"id":"uk-014","cat":"signs","jurisdiction":["UK"],"concept":"motorway-red-x","q":"A red X is displayed above your motorway lane. What does it mean?","choices":["The lane is for overtaking only","The lane is closed and you must move to an open lane","The speed limit has ended","The hard shoulder is open"],"a":1,"why":"A red X marks a closed lane. Follow the signs into an open lane and do not drive in the closed lane.","sourceId":"uk-highway-code","sourceSection":"Motorways — Rule 258"},
      {"id":"uk-015","cat":"signs","jurisdiction":["UK"],"concept":"headlight-flash","q":"What is the correct meaning of flashing your headlights at another road user?","choices":["You are giving them priority","They should speed up","You are making them aware that you are there","You are telling them the road is clear"],"a":2,"why":"The Highway Code says headlight flashes should only be used to let other road users know you are there, not as an invitation to proceed.","sourceId":"uk-highway-code","sourceSection":"General rules — Rules 110 to 111"},
      {"id":"uk-016","cat":"signs","jurisdiction":["UK"],"concept":"blue-circle-sign","q":"What does a blue circular traffic sign usually mean in Great Britain?","choices":["A warning of danger ahead","A tourist attraction","A temporary diversion","A positive mandatory instruction or a route for specified traffic"],"a":3,"why":"Blue circles generally give positive instructions, such as turning in a stated direction, or indicate a route reserved for specified classes of traffic.","sourceId":"uk-know-your-traffic-signs","sourceSection":"The signing system"},
      {"id":"uk-017","cat":"markings","jurisdiction":["UK"],"concept":"hazard-warning-line","q":"A broken white centre line becomes longer with shorter gaps. What should you expect?","choices":["A hazard ahead","A motorway is beginning","Parking is permitted","The road becomes one-way"],"a":0,"why":"Longer centre-line markings with shorter gaps warn that a hazard is ahead, so reassess speed and visibility before crossing the line.","sourceId":"uk-highway-code","sourceSection":"Lines and lane markings — Rule 127"},
      {"id":"uk-018","cat":"markings","jurisdiction":["UK"],"concept":"solid-double-white","q":"The white line nearest you in a double-white-line system is solid. What is the general rule?","choices":["You may cross it whenever traffic is light","You must not cross or straddle it except for specific permitted situations","You must drive on the line","It marks a bus lane"],"a":1,"why":"A solid white line nearest you generally must not be crossed or straddled, with only limited exceptions set out in the Highway Code.","sourceId":"uk-highway-code","sourceSection":"Lines and lane markings — Rule 129"},
      {"id":"uk-019","cat":"markings","jurisdiction":["UK"],"concept":"solid-chevron-area","q":"A chevron area is bordered by solid white lines. When may you enter it?","choices":["Whenever you are overtaking","To queue for a right turn","Only in an emergency","Whenever the lane beside it is busy"],"a":2,"why":"Chevron areas bordered by solid white lines must not be entered except in an emergency.","sourceId":"uk-highway-code","sourceSection":"Lines and lane markings — Rule 130"},
      {"id":"uk-020","cat":"markings","jurisdiction":["UK"],"concept":"road-studs-amber","q":"On a motorway or dual carriageway, what do amber reflective road studs mark?","choices":["The left edge of the road","A slip-road edge","Temporary road works only","The central reservation"],"a":3,"why":"Amber studs mark the central reservation. Red marks the left edge, while green is used at lay-bys and slip roads.","sourceId":"uk-highway-code","sourceSection":"Lines and lane markings — Rule 132"},
      {"id":"uk-021","cat":"markings","jurisdiction":["UK"],"concept":"double-yellow-lines","q":"What do double yellow lines normally mean?","choices":["No waiting at any time","No overtaking","No entry for cars","Parking for permit holders only"],"a":0,"why":"Double yellow lines indicate a prohibition of waiting at any time, unless signs specifically show a seasonal exception.","sourceId":"uk-highway-code","sourceSection":"Waiting and parking — Rule 238"},
      {"id":"uk-022","cat":"row","jurisdiction":["UK"],"concept":"junction-pedestrian-priority","q":"You are turning into a side road where a pedestrian is waiting to cross. What should you do?","choices":["Turn before they step out","Give way to the pedestrian","Sound your horn so they wait","Only give way if there is a zebra crossing"],"a":1,"why":"At junctions, drivers should give way to pedestrians crossing or waiting to cross a road into which or from which they are turning.","sourceId":"uk-highway-code","sourceSection":"Using the road — Rule 170"},
      {"id":"uk-023","cat":"row","jurisdiction":["UK"],"concept":"indicator-not-guarantee","q":"A vehicle approaching from your right is signalling left as you wait at a junction. What is safest?","choices":["Pull out immediately","Assume it will stop","Wait until you are satisfied it is actually turning","Flash your headlights and go"],"a":2,"why":"Do not assume a signal is reliable or has been cancelled correctly. Wait until you are satisfied the vehicle is really turning before emerging.","sourceId":"uk-highway-code","sourceSection":"Using the road — Rule 170"},
      {"id":"uk-024","cat":"row","jurisdiction":["UK"],"concept":"mini-roundabout","q":"At a mini-roundabout, how should you treat the central marking?","choices":["Drive across it to shorten your route","Stop on it before turning right","Ignore it when the road is quiet","Pass around it unless your vehicle is physically unable to do so"],"a":3,"why":"Vehicles must pass around the central markings of a mini-roundabout, except large vehicles that are physically incapable of doing so.","sourceId":"uk-highway-code","sourceSection":"Using the road — Rule 188"},
      {"id":"uk-025","cat":"row","jurisdiction":["UK"],"concept":"green-light-clear-way","q":"Your traffic light turns green but the junction ahead is blocked. What should you do?","choices":["Wait until there is space to proceed safely","Enter the junction because green gives priority","Use the horn until traffic moves","Move into the junction and stop there"],"a":0,"why":"Wait until there is space to proceed safely. A green signal lets you go only when the way ahead is clear; it does not make a blocked junction safe to enter.","sourceId":"uk-highway-code","sourceSection":"Light signals controlling traffic"},
      {"id":"uk-026","cat":"row","jurisdiction":["UK"],"concept":"authorised-person-signals","q":"A uniformed traffic officer signals you to stop. What must you do?","choices":["Continue if the traffic light is green","Obey the signal and stop when safe","Stop only if a police car is present","Ignore it on a dual carriageway"],"a":1,"why":"Drivers must obey lawful signals from authorised officers, including police, traffic officers and DVSA officers.","sourceId":"uk-highway-code","sourceSection":"General rules — Rules 105 to 108"},
      {"id":"uk-027","cat":"row","jurisdiction":["UK"],"concept":"roundabout-cyclist-space","q":"A cyclist is continuing around a roundabout in the left-hand lane. What should you do?","choices":["Pass within the same lane","Cut across before they reach your exit","Give them room and do not cut across their path","Sound the horn so they move left"],"a":2,"why":"Cyclists may remain in the left-hand lane while continuing around a roundabout. Drivers should give them space and avoid cutting across their path.","sourceId":"uk-highway-code","sourceSection":"Using the road — Rule 185"},
      {"id":"uk-028","cat":"speed","jurisdiction":["UK"],"concept":"wales-built-up-speed","q":"In Wales, what speed limit generally applies to a lit built-up road when signs do not show a different limit?","choices":["30 mph","40 mph","60 mph","20 mph"],"a":3,"why":"In Wales, 20 mph generally applies on roads with street lights unless signs show a different limit.","sourceId":"uk-highway-code","sourceSection":"Speed limits — Rule 124"},
      {"id":"uk-029","cat":"speed","jurisdiction":["UK"],"concept":"speed-limit-not-target","q":"A road is signed at 60 mph, but visibility is poor. What does the 60 mph sign mean?","choices":["60 mph is the maximum, not a target; you may need to drive slower","You must stay as close to 60 mph as possible","You may exceed 60 mph while overtaking","The limit applies only in dry weather"],"a":0,"why":"A speed limit is an absolute maximum, not a target. Drivers should reduce speed when road, traffic, visibility or weather conditions require it.","sourceId":"uk-highway-code","sourceSection":"Speed limits — Rule 125"},
      {"id":"uk-030","cat":"speed","jurisdiction":["UK"],"concept":"trailer-single-carriageway-speed","q":"What is the national speed limit for a car towing a trailer on a single carriageway?","choices":["60 mph","50 mph","70 mph","40 mph"],"a":1,"why":"Cars towing trailers are limited to 50 mph on single carriageways under the national speed-limit table.","sourceId":"uk-highway-code","sourceSection":"Speed limits — Rule 124"},
      {"id":"uk-031","cat":"speed","jurisdiction":["UK"],"concept":"trailer-motorway-speed","q":"What is the national maximum for a car towing a trailer on a motorway?","choices":["70 mph","50 mph","60 mph","80 mph"],"a":2,"why":"Cars towing caravans or trailers are limited to 60 mph on motorways and dual carriageways.","sourceId":"uk-highway-code","sourceSection":"Speed limits — Rule 124"},
      {"id":"uk-032","cat":"speed","jurisdiction":["UK"],"concept":"icy-stopping-distance","q":"Compared with a dry road, how much greater can stopping distance be on ice?","choices":["About the same","Up to twice as great","Up to five times as great","Up to ten times as great"],"a":3,"why":"The Highway Code warns that stopping distances on icy roads can be up to ten times greater than on dry roads.","sourceId":"uk-highway-code","sourceSection":"Driving in adverse weather — Rule 230"},
      {"id":"uk-033","cat":"parking","jurisdiction":["UK"],"concept":"parking-crossing-zigzags","q":"May you park on the zig-zag markings at a pedestrian crossing?","choices":["No, parking there is prohibited","Yes, for up to five minutes","Only after dark","Only with hazard lights on"],"a":0,"why":"Parking is prohibited on a pedestrian crossing and in the area covered by its zig-zag lines because a parked vehicle can hide pedestrians from approaching traffic.","sourceId":"uk-highway-code","sourceSection":"Pedestrian crossings — Rule 191"},
      {"id":"uk-034","cat":"parking","jurisdiction":["UK"],"concept":"parking-near-junction","q":"Unless you are in an authorised parking space, how close should you avoid parking to a junction?","choices":["Within 2 metres","Within 10 metres","Within 25 metres","Within 50 metres"],"a":1,"why":"The Highway Code says not to stop or park opposite or within 10 metres of a junction, except in an authorised parking space.","sourceId":"uk-highway-code","sourceSection":"Waiting and parking — Rule 243"},
      {"id":"uk-035","cat":"parking","jurisdiction":["UK"],"concept":"night-parking-direction","q":"At night, when may you park facing against the direction of traffic flow?","choices":["Whenever your sidelights are on","On any road below 30 mph","Only in a recognised parking space","Whenever the road is empty"],"a":2,"why":"At night you must not park facing against the traffic flow unless you are in a recognised parking space.","sourceId":"uk-highway-code","sourceSection":"Waiting and parking — Rule 248"},
      {"id":"uk-036","cat":"parking","jurisdiction":["UK"],"concept":"parking-lights-high-speed-road","q":"Your car is parked at night on a road with a speed limit above 30 mph. What is required?","choices":["Hazard lights must flash all night","No lights are needed if you are near the kerb","Main beam headlights must stay on","Parking lights must be displayed"],"a":3,"why":"Vehicles parked at night on a road or lay-by with a speed limit above 30 mph must display parking lights.","sourceId":"uk-highway-code","sourceSection":"Waiting and parking — Rule 249"},
      {"id":"uk-037","cat":"parking","jurisdiction":["UK"],"concept":"hill-parking-downhill","q":"When parking facing downhill on a hill, which way should you turn the steering wheel?","choices":["Towards the kerb","Away from the kerb","Keep the wheels straight","It does not matter if the handbrake is on"],"a":0,"why":"When facing downhill, the Highway Code says to select reverse gear and turn the wheels towards the kerb; when facing uphill, turn them away from the kerb.","sourceId":"uk-highway-code","sourceSection":"Waiting and parking — Rule 252"},
      {"id":"uk-038","cat":"alcohol","jurisdiction":["UK"],"concept":"medicines-and-driving","q":"A medicine may make you drowsy or impair your driving. What should you do?","choices":["Drive only on quiet roads","Check with a doctor or pharmacist and do not drive if advised you may be impaired","Take extra caffeine and continue","Ignore the warning if the medicine is prescribed"],"a":1,"why":"The Highway Code says you must not drive under the influence of drugs or medicine. Check with a doctor or pharmacist and do not drive if you may be impaired.","sourceId":"uk-highway-code","sourceSection":"Rules for drivers — Rule 96"},
      {"id":"uk-039","cat":"safety","jurisdiction":["UK"],"concept":"tired-driving-break","q":"On a long journey, what minimum break does the Highway Code recommend after every two hours of driving?","choices":["5 minutes","10 minutes","At least 15 minutes","30 minutes"],"a":2,"why":"To reduce fatigue risk, the Highway Code recommends planning a minimum break of at least 15 minutes after every two hours of driving.","sourceId":"uk-highway-code","sourceSection":"Rules for drivers — Rule 91"},
      {"id":"uk-040","cat":"safety","jurisdiction":["UK"],"concept":"fog-light-use","q":"When should front or rear fog lights be used?","choices":["Whenever it is raining","Whenever you are on a motorway","At night on every unlit road","Only when visibility is seriously reduced, and they should be switched off when it improves"],"a":3,"why":"Fog lights may be used when visibility is seriously reduced, generally below about 100 metres, and must be switched off when visibility improves.","sourceId":"uk-highway-code","sourceSection":"Driving in adverse weather — Rules 226 and 236"},
      {"id":"uk-041","cat":"safety","jurisdiction":["UK"],"concept":"wet-stopping-distance","q":"In wet weather, how should you expect stopping distance to compare with dry conditions?","choices":["It can be at least double","It is usually shorter","It stays exactly the same","It is only longer below 30 mph"],"a":0,"why":"Wet roads reduce tyre grip, so stopping distances will be at least double those required on dry roads.","sourceId":"uk-highway-code","sourceSection":"Driving in adverse weather — Rule 227"},
      {"id":"uk-042","cat":"safety","jurisdiction":["UK"],"concept":"hazard-warning-lights-moving","q":"When may hazard warning lights be used while a vehicle is moving?","choices":["Whenever traffic is slow","On a motorway or unrestricted dual carriageway to warn following drivers of a hazard or obstruction ahead","Whenever a driver wants to stop briefly","Every time a vehicle overtakes"],"a":1,"why":"While moving, hazard warning lights are only for a motorway or unrestricted dual carriageway when warning drivers behind of a hazard or obstruction ahead.","sourceId":"uk-highway-code","sourceSection":"General rules — Rule 116"},
      {"id":"uk-043","cat":"safety","jurisdiction":["UK"],"concept":"rear-facing-seat-airbag","q":"Where must a rear-facing baby seat not be fitted?","choices":["On a rear seat with a head restraint","On a seat with a three-point belt","In front of an active frontal airbag","Next to a window"],"a":2,"why":"A rear-facing baby seat must not be fitted where an active frontal airbag protects that seat because deployment can cause serious injury.","sourceId":"uk-highway-code","sourceSection":"Rules for drivers — Rule 101"},
      {"id":"uk-044","cat":"safety","jurisdiction":["UK"],"concept":"collision-casualty-movement","q":"After a collision, when should an injured casualty normally be moved from a vehicle?","choices":["As soon as another driver arrives","Immediately, to make them comfortable","Before calling emergency services","Only if there is a threat of further danger"],"a":3,"why":"The Highway Code first-aid guidance says not to move casualties from vehicles unless there is a threat of further danger.","sourceId":"uk-highway-code","sourceSection":"Annex 7 — First aid on the road"},
      {"id":"uk-045","cat":"safety","jurisdiction":["UK"],"concept":"seriously-reduced-visibility-headlights","q":"Visibility drops below about 100 metres in heavy fog. What lighting is required?","choices":["Headlights","Parking lights only","Hazard lights continuously","No lights during daylight"],"a":0,"why":"Headlights must be used when visibility is seriously reduced, generally when you cannot see for more than 100 metres.","sourceId":"uk-highway-code","sourceSection":"Driving in adverse weather — Rule 226"},
      {"id":"uk-046","cat":"safety","jurisdiction":["UK"],"concept":"motorway-breakdown-safer-place","q":"A vehicle develops a problem on a motorway but can still reach a safer stopping place. What does the Highway Code advise?","choices":["Stop in the live lane","Leave at the next exit or pull into a service area if possible","Reverse to the previous exit","Stop on the central reservation"],"a":1,"why":"If possible, leave the motorway at the next exit or reach a service area, which is safer than stopping close to high-speed traffic.","sourceId":"uk-highway-code","sourceSection":"Breakdowns and incidents — Rule 277"},
      {"id":"uk-047","cat":"vulnerable","jurisdiction":["UK"],"concept":"hierarchy-road-users","q":"Under the Highway Code hierarchy of road users, who has the greatest responsibility to reduce danger?","choices":["The person travelling fastest","The person who arrived first","The road users who can cause the greatest harm","Only professional drivers"],"a":2,"why":"The hierarchy says road users who can cause the greatest harm have the greatest responsibility to reduce the danger they pose to others.","sourceId":"uk-highway-code","sourceSection":"Introduction — Hierarchy of road users"},
      {"id":"uk-048","cat":"vulnerable","jurisdiction":["UK"],"concept":"horse-passing-distance","q":"When passing a horse rider, what guide does the Highway Code give?","choices":["Pass at up to 30 mph with 1 metre","Sound the horn and pass quickly","Use the opposite verge if needed","Pass at under 10 mph and allow at least 2 metres of space"],"a":3,"why":"When passing horse riders or horse-drawn vehicles, the Highway Code advises speeds under 10 mph and at least 2 metres of space.","sourceId":"uk-highway-code","sourceSection":"Using the road — Rule 163"},
      {"id":"uk-049","cat":"vehicle","jurisdiction":["UK"],"concept":"tyre-tread-depth","q":"What is the minimum legal tyre tread depth for a car across the central three-quarters of the tread?","choices":["1.6 mm","1.0 mm","2.5 mm","3.0 mm"],"a":0,"why":"Cars and light vans must have at least 1.6 mm of tread across the central three-quarters of the tyre and around the entire circumference.","sourceId":"uk-highway-code","sourceSection":"Annex 6 — Tyres"},
      {"id":"uk-050","cat":"vehicle","jurisdiction":["UK"],"concept":"tyre-pressure-check","q":"When is the best time to check tyre pressures?","choices":["Immediately after a long motorway journey","Before a journey while the tyres are cold","Only when a warning light appears","After washing the vehicle"],"a":1,"why":"The Highway Code advises checking tyre pressures weekly, before a journey and while the tyres are cold because warm tyres can give a misleading reading.","sourceId":"uk-highway-code","sourceSection":"Annex 6 — Tyre pressures"},
      {"id":"uk-051","cat":"vehicle","jurisdiction":["UK"],"concept":"warning-lights","q":"A warning light that normally goes out after the engine starts stays illuminated. What should you do?","choices":["Cover it so it does not distract you","Drive faster to recharge the system","Stop and investigate the problem safely","Ignore it until the next service"],"a":2,"why":"Warning lights that stay on or appear while driving can indicate a serious fault. Stop safely and investigate rather than ignoring them.","sourceId":"uk-highway-code","sourceSection":"Annex 6 — Warning displays"},
      {"id":"uk-052","cat":"vehicle","jurisdiction":["UK"],"concept":"secure-load","q":"Before driving with luggage in the vehicle, what should you do?","choices":["Put heavy items on the parcel shelf","Leave loose items where they can be reached","Place everything on the front passenger seat","Securely stow the luggage"],"a":3,"why":"Items of luggage should be securely stowed so they cannot move around the vehicle or become dangerous in sudden braking or a collision.","sourceId":"uk-highway-code","sourceSection":"Annex 6 — Vehicle maintenance"},
      {"id":"uk-053","cat":"laws","jurisdiction":["UK"],"concept":"eyesight-number-plate","q":"In good daylight, from what distance must a driver be able to read a modern vehicle number plate?","choices":["20 metres","10 metres","30 metres","50 metres"],"a":0,"why":"Drivers must be able to read a modern number plate in good daylight from 20 metres, wearing any glasses or contact lenses needed for driving.","sourceId":"uk-highway-code","sourceSection":"Rules for drivers — Rule 92"},
      {"id":"uk-054","cat":"laws","jurisdiction":["UK"],"concept":"missed-motorway-exit","q":"You miss your motorway exit. What should you do?","choices":["Reverse along the hard shoulder","Continue to the next exit","Make a U-turn through the central reservation","Stop and wait for a gap to reverse"],"a":1,"why":"You must not reverse, cross the central reservation or drive against traffic on a motorway. If you miss an exit, continue to the next one.","sourceId":"uk-highway-code","sourceSection":"Motorways — Rule 263"},
      {"id":"uk-055","cat":"laws","jurisdiction":["UK"],"concept":"hard-shoulder-use","q":"When may you normally use a motorway hard shoulder?","choices":["Whenever traffic is slow","To make a phone call","Only in an emergency or when directed by police, traffic officers or signs","To overtake a slow vehicle"],"a":2,"why":"The hard shoulder must not be used except in an emergency or when directed by police, traffic officers or traffic signs.","sourceId":"uk-highway-code","sourceSection":"Motorways — Rule 269"},
      {"id":"uk-056","cat":"laws","jurisdiction":["UK"],"concept":"emergency-area-use","q":"What are motorway emergency areas for?","choices":["Routine rest breaks","Loading passengers","Checking a route on your phone","Emergencies only"],"a":3,"why":"Emergency areas are for emergencies only. They are marked by blue signs with an orange SOS telephone symbol and may have orange surfacing.","sourceId":"uk-highway-code","sourceSection":"Motorways — Rule 270"},
      {"id":"uk-057","cat":"vulnerable","jurisdiction":["UK"],"concept":"cyclist-primary-position","q":"Why might a cyclist ride in the centre of the lane on a narrow road or near a junction?","choices":["It can be the safest position for visibility and space","They are required to block overtaking","It means they are turning right","It is only allowed at night"],"a":0,"why":"Cyclists may ride in the centre of a lane on narrow roads, quiet streets, near junctions or in slower traffic because it can help them see, be seen and avoid unsafe close passes.","sourceId":"uk-highway-code","sourceSection":"Road users requiring extra care — Rule 213"},
      {"id":"uk-058","cat":"vulnerable","jurisdiction":["UK"],"concept":"passing-animals","q":"When passing animals on the road, what should you avoid?","choices":["Reducing speed","Sounding the horn or revving the engine","Leaving extra room","Being ready to stop"],"a":1,"why":"Drive slowly around animals, give them room and be ready to stop. Do not frighten them by sounding the horn, revving or accelerating sharply.","sourceId":"uk-highway-code","sourceSection":"Road users requiring extra care — Rule 214"},
      {"id":"uk-059","cat":"laws","jurisdiction":["UK"],"concept":"pre-drive-documents","q":"Before setting off, what must you ensure about your authority to drive the vehicle?","choices":["You have a valid licence and insurance for that vehicle","You have owned the vehicle for at least a week","You have a printed map in the glovebox","You have paid for roadside assistance"],"a":0,"why":"Before setting off, you must ensure that you have a valid driving licence and insurance for the vehicle you intend to use.","sourceId":"uk-highway-code","sourceSection":"Before setting off — Rule 97"},
      {"id":"uk-060","cat":"safety","jurisdiction":["UK"],"concept":"seat-belt-use","q":"A seat belt is fitted to your seat in a car. What is the general rule?","choices":["Use it only on roads above 30 mph","Use it only on long journeys","You must wear it unless a specific exemption applies","It is optional for adult passengers"],"a":2,"why":"Where a seat belt is fitted, it must generally be worn. The Highway Code lists limited legal exemptions, but ordinary journeys are not exempt.","sourceId":"uk-highway-code","sourceSection":"Seat belts and child restraints — Rule 99"}
    ],
  },
};

const PACK_IDS = Object.keys(STATE_PACKS);

/** Every jurisdiction-tagged question across all packs, flattened. */
function allPackQuestions() {
  return PACK_IDS.flatMap((id) => STATE_PACKS[id].questions || []);
}

/** Questions tagged with `jurisdiction:["CA",...]` belong to specific packs;
    untagged questions are universal to the US bank. The UK bank is
    country-scoped: only UK-tagged questions apply (US universal rules such as
    right-on-red and US BAC limits must never leak into UK study). */
function filterBankForPack(questions, packId) {
  if (!packId || packId === "generic") return questions.filter((q) => !q.jurisdiction);
  const pack = STATE_PACKS[packId];
  const includeUniversal = !pack || pack.includeUniversal !== false;
  return questions.filter((q) =>
    (includeUniversal && (!Array.isArray(q.jurisdiction) || !q.jurisdiction.length)) ||
    (Array.isArray(q.jurisdiction) && q.jurisdiction.includes(packId))
  );
}

function packFacts(packId) {
  return (STATE_PACKS[packId] || STATE_PACKS.generic).facts;
}

function sourceForQuestion(question) {
  return question && question.sourceId ? SOURCE_REGISTRY[question.sourceId] || null : null;
}

function packSource(packId) {
  const pack = STATE_PACKS[packId] || STATE_PACKS.generic;
  return pack.sourceId ? SOURCE_REGISTRY[pack.sourceId] || null : null;
}

const RoadReadyPacks = {
  SOURCE_REGISTRY, UNIVERSAL_DEFAULTS, CONCEPT_FACT_KEYS, VERIFICATION_MAX_AGE_DAYS,
  STATE_PACKS, PACK_IDS, filterBankForPack, packFacts,
  allPackQuestions, sourceForQuestion, packSource,
};
if (typeof module !== "undefined" && module.exports) module.exports = RoadReadyPacks;
else if (typeof globalThis !== "undefined") globalThis.RoadReadyPacks = RoadReadyPacks;
