#!/usr/bin/env node
/* Road Ready — product statistics as code (source of truth).
 *
 * The README used to carry hand-written content figures (question counts,
 * sign counts, hazard scenario counts), which drifted whenever content grew.
 * This script derives every figure from the actual source modules and then
 * either:
 *   --write   rewrites the generated block AND the figure-bearing README
 *             sentences in place (one command fixes all drift)
 *   --check   fails when any documented figure differs from the code
 *   (none)    prints the derived figures
 *
 * The check runs in `npm test`, so documented drift cannot reach main.
 *
 * Figures are derived, never hardcoded:
 *   - question banks   via scripts/content-loader.mjs (the same loader the
 *                      content QA pipeline uses)
 *   - hazard scenarios via js/hazard-scenarios.js (the shipped scenario bank)
 *   - test files       via the tests directory listing
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import { loadContent } from "./content-loader.mjs";

const nodeRequire = createRequire(import.meta.url);

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const README_PATH = path.join(ROOT, "README.md");
const BLOCK_BEGIN = "<!-- product-stats:begin -->";
const BLOCK_END = "<!-- product-stats:end -->";

/** Derive every product figure from the source modules. Pure of the README. */
export function derive() {
  const data = loadContent();
  const all = [...data.QUESTIONS];
  const universal = all.filter((q) => !Array.isArray(q.jurisdiction) || !q.jurisdiction.length);
  const gb = data.STATE_PACKS.UK.questions;
  const gbConcepts = new Set(gb.map((q) => q.concept).filter(Boolean)).size;
  const forms = new Set(all.map((q) => q.form || "recall"));
  const signs = Object.keys(data.SIGNS).length;

  // Hazard scenario bank ships as a CommonJS module (js/hazard-scenarios.js).
  const hazard = nodeRequire(path.join(ROOT, "js", "hazard-scenarios.js"));
  const scenarios = (hazard.scenarios || []).length;
  const multiHazard = (hazard.scenarios || []).filter((s) => s.multi).length;

  const countries = Object.values(data.JURISDICTIONS || {}).filter((c) => c && c.active);
  const regionPacks = countries.reduce((t, c) => t + (c.regions ? c.regions.length : 0), 0);

  let testFiles = 0;
  try {
    testFiles = readdirSync(path.join(ROOT, "tests"))
      .filter((f) => /\.test\.(js|mjs)$/.test(f)).length;
  } catch { /* tests dir optional in packaged builds */ }

  return {
    totalQuestions: all.length,
    universalQuestions: universal.length,
    gbQuestions: gb.length,
    gbConcepts,
    questionForms: forms.size,
    signs,
    scenarios,
    multiHazard,
    countries: countries.length,
    regionPacks,
    testFiles,
  };
}

/**
 * Documented claims to police. Each pattern must MATCH the README (so a
 * claim cannot be silently deleted) and each captured figure must equal the
 * derived value. `values` maps capture-group index (1-based) to figure key.
 */
const CLAIMS = [
  { name: "universal questions", pattern: /(\d+) universal U\.S\. questions/, values: { 1: "universalQuestions" } },
  { name: "total verified questions", pattern: /\((\d+) verified questions total\)/, values: { 1: "totalQuestions" } },
  { name: "GB question count", pattern: /car-theory pack with a (\d+)-question verified bank/, values: { 1: "gbQuestions" } },
  { name: "GB bank figures", pattern: /is (\d+) questions across (\d+) concepts/, values: { 1: "gbQuestions", 2: "gbConcepts" } },
  { name: "question forms", pattern: /spanning (\d+) \*\*question forms\*\*/, values: { 1: "questionForms" } },
  { name: "hazard scenario count", pattern: /(\d+) original animated scenarios/, values: { 1: "scenarios" } },
  { name: "sign count", pattern: /(\d+) hand-drawn SVG road signs/, values: { 1: "signs" } },
];

/** The generated block — the single canonical place figures live in prose. */
function generatedBlock(f) {
  return [
    BLOCK_BEGIN,
    "<!-- Generated by scripts/product-stats.mjs — do not edit by hand. Run: npm run stats:update -->",
    "",
    "| Figure | Count |",
    "|---|---|",
    `| Universal U.S. theory questions | ${f.universalQuestions} |`,
    `| Great Britain (DVSA car) questions | ${f.gbQuestions} |`,
    `| Great Britain concepts | ${f.gbConcepts} |`,
    `| Verified questions, all packs | ${f.totalQuestions} |`,
    `| Road signs (jurisdiction-aware artwork) | ${f.signs} |`,
    `| Hazard-perception scenarios (original) | ${f.scenarios} |`,
    `| — of which multi-hazard scenes | ${f.multiHazard} |`,
    `| Question forms in use | ${f.questionForms} |`,
    `| Active jurisdiction modules | ${f.countries} |`,
    `| Region packs incl. Great Britain | ${f.regionPacks} |`,
    `| Unit test files | ${f.testFiles} |`,
    "",
    BLOCK_END,
  ].join("\n");
}

/** Insert or replace the generated block in the README text. */
function applyBlock(readme, f) {
  const block = generatedBlock(f);
  if (readme.includes(BLOCK_BEGIN) && readme.includes(BLOCK_END)) {
    const start = readme.indexOf(BLOCK_BEGIN);
    const end = readme.indexOf(BLOCK_END) + BLOCK_END.length;
    return readme.slice(0, start) + block + readme.slice(end);
  }
  // First run: place the block directly after the product-decision section.
  const anchor = "## Run it";
  const at = readme.indexOf(anchor);
  const header = `## Product statistics\n\n${block}\n\n`;
  return at === -1 ? readme + "\n\n" + header : readme.slice(0, at) + header + readme.slice(at);
}

/** Rewrite every claim's captured figure to its derived value. */
function applyClaims(readme, f) {
  let out = readme;
  for (const claim of CLAIMS) {
    out = out.replace(claim.pattern, (whole, ...groups) => {
      let fixed = whole;
      for (const [groupIdx, key] of Object.entries(claim.values)) {
        const i = Number(groupIdx) - 1;
        const current = groups[i];
        const derived = String(f[key]);
        if (current !== derived) fixed = fixed.replace(current, derived);
      }
      return fixed;
    });
  }
  return out;
}

/** Check the README against derived figures. Returns a list of problems. */
export function checkReadme(readme, f) {
  const problems = [];
  if (!readme.includes(BLOCK_BEGIN) || !readme.includes(BLOCK_END)) {
    problems.push("generated product-statistics block is missing from README.md");
  } else {
    const start = readme.indexOf(BLOCK_BEGIN);
    const end = readme.indexOf(BLOCK_END) + BLOCK_END.length;
    const actual = readme.slice(start, end).replace(/\r\n/g, "\n").trim();
    const expected = generatedBlock(f).replace(/\r\n/g, "\n").trim();
    if (actual !== expected) {
      problems.push("generated product-statistics block is stale — run: npm run stats:update");
    }
  }
  for (const claim of CLAIMS) {
    const m = readme.match(claim.pattern);
    if (!m) {
      problems.push(`documented claim "${claim.name}" is missing from README.md`);
      continue;
    }
    for (const [groupIdx, key] of Object.entries(claim.values)) {
      const documented = Number(m[Number(groupIdx)]);
      if (documented !== f[key]) {
        problems.push(`README says ${documented} for "${claim.name}" but the code has ${f[key]} — run: npm run stats:update`);
      }
    }
  }
  return problems;
}

/* ---------------- CLI ---------------- */
if (process.argv[1] && process.argv[1].endsWith("product-stats.mjs")) {
  const mode = process.argv.includes("--write") ? "write"
    : process.argv.includes("--check") ? "check" : "print";
  const f = derive();
  const readme = readFileSync(README_PATH, "utf8");

  if (mode === "write") {
    const updated = applyClaims(applyBlock(readme, f), f);
    writeFileSync(README_PATH, updated);
    console.log(`product-stats: README.md updated from source modules (${f.totalQuestions} questions, ${f.signs} signs, ${f.scenarios} scenarios)`);
    const problems = checkReadme(updated, f);
    if (problems.length) {
      console.error("product-stats: STILL STALE after update:");
      for (const p of problems) console.error(`  - ${p}`);
      process.exit(1);
    }
    console.log("product-stats: README figures match the code");
    process.exit(0);
  }

  if (mode === "check") {
    const problems = checkReadme(readme, f);
    if (problems.length) {
      console.error("product-stats: README/product-stat mismatch:");
      for (const p of problems) console.error(`  - ${p}`);
      process.exit(1);
    }
    console.log(`product-stats: README figures match the code (${f.totalQuestions} questions, ${f.signs} signs, ${f.scenarios} scenarios)`);
    process.exit(0);
  }

  for (const [k, v] of Object.entries(f)) console.log(`${k}: ${v}`);
}
