#!/usr/bin/env node
/* Road Ready — automated content QA system (CLI).
 *
 *   node scripts/validate-content.mjs [--update-manifest] [--strict]
 *
 * Runs scripts/content-checks.mjs against the real bank and additionally
 * manages the provenance manifest (content-manifest.json): a stable hash per
 * question plus bank-level metadata. `--update-manifest` regenerates it;
 * otherwise uncommitted drift from the manifest fails the build.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadContent } from "./content-loader.mjs";
import { runChecks, canonicalQuestion } from "./content-checks.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const UPDATE = process.argv.includes("--update-manifest");
const STRICT = process.argv.includes("--strict");
const MANIFEST_PATH = path.join(ROOT, "content-manifest.json");

const data = loadContent();
const { QUESTIONS } = data;
const { errors, warnings, stats } = runChecks(data);

/* ---------- provenance ---------- */
const hashQuestion = (q) => createHash("sha256").update(canonicalQuestion(q)).digest("hex").slice(0, 16);
const bankHash = () => createHash("sha256").update(QUESTIONS.map(canonicalQuestion).sort().join("\n")).digest("hex").slice(0, 32);

if (UPDATE) {
  const prev = existsSync(MANIFEST_PATH) ? JSON.parse(readFileSync(MANIFEST_PATH, "utf8")) : {};
  const prevQuestions = prev.questions || {};
  const today = new Date().toISOString().slice(0, 10);
  const questions = {};
  for (const q of QUESTIONS) {
    const prior = prevQuestions[q.id];
    questions[q.id] = {
      hash: hashQuestion(q),
      firstSeen: (prior && prior.firstSeen) || today,
      lastChecked: today,
      source: typeof q.source === "string" ? q.source : (prior && prior.source) || "general-us-dmv-handbook",
    };
  }
  const manifest = {
    _comment: "Generated by scripts/validate-content.mjs — do not edit by hand. Run: npm run provenance:update",
    generatedAt: today,
    bankHash: bankHash(),
    questionCount: QUESTIONS.length,
    questions,
  };
  writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 1) + "\n");
  console.log(`provenance: wrote ${MANIFEST_PATH} (${Object.keys(questions).length} questions)`);
} else if (existsSync(MANIFEST_PATH)) {
  try {
    const m = JSON.parse(readFileSync(MANIFEST_PATH, "utf8"));
    if (m.bankHash !== bankHash()) {
      errors.push({ rule: "provenance", msg: `question bank changed since the manifest was generated — run "npm run provenance:update" and commit the result` });
    }
    const knownIds = new Set(QUESTIONS.map((q) => q.id));
    const orphaned = Object.keys(m.questions || {}).filter((id) => !knownIds.has(id));
    if (orphaned.length) warnings.push({ rule: "provenance", msg: `manifest tracks removed questions: ${orphaned.join(", ")}` });
  } catch (e) {
    errors.push({ rule: "provenance", msg: `content-manifest.json unreadable: ${e.message}` });
  }
} else {
  warnings.push({ rule: "provenance", msg: `no content-manifest.json yet — run "npm run provenance:update"` });
}

const missingSource = QUESTIONS.filter((q) => typeof q.source !== "string" || !q.source.trim());
if (missingSource.length) {
  warnings.push({ rule: "provenance", review: true, msg: `${missingSource.length}/${QUESTIONS.length} questions have no explicit "source" field (manifest still tracks their content hash)` });
}

/* ---------- report ---------- */
console.log(`\nRoad Ready content QA — ${stats.questions} questions, ${stats.signs} signs, ${stats.packs} packs`);
const fmt = (list) => {
  const byRule = {};
  list.forEach(({ rule, msg }) => { (byRule[rule] = byRule[rule] || []).push(msg); });
  let out = "";
  for (const [rule, msgs] of Object.entries(byRule)) {
    out += `\n  [${rule}]`;
    for (const msg of msgs) out += `\n    - ${msg}`;
  }
  return out;
};
if (errors.length) console.log(`\nERRORS (${errors.length}):${fmt(errors)}`);
// --strict blocks on errors + non-review warnings; advisory "review" notes never fail CI
const blockingWarnings = warnings.filter((w) => !w.review);
if (warnings.length) console.log(`\nWarnings (${warnings.length}):${fmt(warnings)}`);

const failing = STRICT ? errors.length + blockingWarnings.length : errors.length;
if (failing > 0) {
  console.log(`\nFAIL`);
  process.exit(1);
}
console.log(`\nPASS (${errors.length} errors, ${blockingWarnings.length} blocking warnings, ${warnings.length - blockingWarnings.length} review notes)`);
